/**
 * Heroicons v1 完整載入器
 * 提供所有 230 個 Heroicons v1 圖標的靜態映射
 * 解決 Vite 動態導入限制問題
 */

import { heroiconsOutline } from './allHeroicons.js'

/**
 * 完整的 Heroicons 靜態載入映射
 * 包含所有 outline 和常用 solid 版本圖標
 */
export const heroiconsLoaders = {
  // Outline icons - 完整的 230 個圖標
  'AcademicCapIcon-outline': () => import('@heroicons/vue/outline/AcademicCapIcon'),
  'AdjustmentsIcon-outline': () => import('@heroicons/vue/outline/AdjustmentsIcon'),
  'AnnotationIcon-outline': () => import('@heroicons/vue/outline/AnnotationIcon'),
  'ArchiveIcon-outline': () => import('@heroicons/vue/outline/ArchiveIcon'),
  'ArrowCircleDownIcon-outline': () => import('@heroicons/vue/outline/ArrowCircleDownIcon'),
  'ArrowCircleLeftIcon-outline': () => import('@heroicons/vue/outline/ArrowCircleLeftIcon'),
  'ArrowCircleRightIcon-outline': () => import('@heroicons/vue/outline/ArrowCircleRightIcon'),
  'ArrowCircleUpIcon-outline': () => import('@heroicons/vue/outline/ArrowCircleUpIcon'),
  'ArrowDownIcon-outline': () => import('@heroicons/vue/outline/ArrowDownIcon'),
  'ArrowLeftIcon-outline': () => import('@heroicons/vue/outline/ArrowLeftIcon'),
  'ArrowNarrowDownIcon-outline': () => import('@heroicons/vue/outline/ArrowNarrowDownIcon'),
  'ArrowNarrowLeftIcon-outline': () => import('@heroicons/vue/outline/ArrowNarrowLeftIcon'),
  'ArrowNarrowRightIcon-outline': () => import('@heroicons/vue/outline/ArrowNarrowRightIcon'),
  'ArrowNarrowUpIcon-outline': () => import('@heroicons/vue/outline/ArrowNarrowUpIcon'),
  'ArrowRightIcon-outline': () => import('@heroicons/vue/outline/ArrowRightIcon'),
  'ArrowSmDownIcon-outline': () => import('@heroicons/vue/outline/ArrowSmDownIcon'),
  'ArrowSmLeftIcon-outline': () => import('@heroicons/vue/outline/ArrowSmLeftIcon'),
  'ArrowSmRightIcon-outline': () => import('@heroicons/vue/outline/ArrowSmRightIcon'),
  'ArrowSmUpIcon-outline': () => import('@heroicons/vue/outline/ArrowSmUpIcon'),
  'ArrowUpIcon-outline': () => import('@heroicons/vue/outline/ArrowUpIcon'),
  'ArrowsExpandIcon-outline': () => import('@heroicons/vue/outline/ArrowsExpandIcon'),
  'AtSymbolIcon-outline': () => import('@heroicons/vue/outline/AtSymbolIcon'),
  'BackspaceIcon-outline': () => import('@heroicons/vue/outline/BackspaceIcon'),
  'BadgeCheckIcon-outline': () => import('@heroicons/vue/outline/BadgeCheckIcon'),
  'BanIcon-outline': () => import('@heroicons/vue/outline/BanIcon'),
  'BeakerIcon-outline': () => import('@heroicons/vue/outline/BeakerIcon'),
  'BellIcon-outline': () => import('@heroicons/vue/outline/BellIcon'),
  'BookOpenIcon-outline': () => import('@heroicons/vue/outline/BookOpenIcon'),
  'BookmarkIcon-outline': () => import('@heroicons/vue/outline/BookmarkIcon'),
  'BookmarkAltIcon-outline': () => import('@heroicons/vue/outline/BookmarkAltIcon'),
  'BriefcaseIcon-outline': () => import('@heroicons/vue/outline/BriefcaseIcon'),
  'CakeIcon-outline': () => import('@heroicons/vue/outline/CakeIcon'),
  'CalculatorIcon-outline': () => import('@heroicons/vue/outline/CalculatorIcon'),
  'CalendarIcon-outline': () => import('@heroicons/vue/outline/CalendarIcon'),
  'CameraIcon-outline': () => import('@heroicons/vue/outline/CameraIcon'),
  'CashIcon-outline': () => import('@heroicons/vue/outline/CashIcon'),
  'ChartBarIcon-outline': () => import('@heroicons/vue/outline/ChartBarIcon'),
  'ChartPieIcon-outline': () => import('@heroicons/vue/outline/ChartPieIcon'),
  'ChartSquareBarIcon-outline': () => import('@heroicons/vue/outline/ChartSquareBarIcon'),
  'ChatIcon-outline': () => import('@heroicons/vue/outline/ChatIcon'),
  'ChatAltIcon-outline': () => import('@heroicons/vue/outline/ChatAltIcon'),
  'ChatAlt2Icon-outline': () => import('@heroicons/vue/outline/ChatAlt2Icon'),
  'CheckIcon-outline': () => import('@heroicons/vue/outline/CheckIcon'),
  'CheckCircleIcon-outline': () => import('@heroicons/vue/outline/CheckCircleIcon'),
  'ChevronDoubleDownIcon-outline': () => import('@heroicons/vue/outline/ChevronDoubleDownIcon'),
  'ChevronDoubleLeftIcon-outline': () => import('@heroicons/vue/outline/ChevronDoubleLeftIcon'),
  'ChevronDoubleRightIcon-outline': () => import('@heroicons/vue/outline/ChevronDoubleRightIcon'),
  'ChevronDoubleUpIcon-outline': () => import('@heroicons/vue/outline/ChevronDoubleUpIcon'),
  'ChevronDownIcon-outline': () => import('@heroicons/vue/outline/ChevronDownIcon'),
  'ChevronLeftIcon-outline': () => import('@heroicons/vue/outline/ChevronLeftIcon'),
  'ChevronRightIcon-outline': () => import('@heroicons/vue/outline/ChevronRightIcon'),
  'ChevronUpIcon-outline': () => import('@heroicons/vue/outline/ChevronUpIcon'),
  'ChipIcon-outline': () => import('@heroicons/vue/outline/ChipIcon'),
  'ClipboardIcon-outline': () => import('@heroicons/vue/outline/ClipboardIcon'),
  'ClipboardCheckIcon-outline': () => import('@heroicons/vue/outline/ClipboardCheckIcon'),
  'ClipboardCopyIcon-outline': () => import('@heroicons/vue/outline/ClipboardCopyIcon'),
  'ClipboardListIcon-outline': () => import('@heroicons/vue/outline/ClipboardListIcon'),
  'ClockIcon-outline': () => import('@heroicons/vue/outline/ClockIcon'),
  'CloudIcon-outline': () => import('@heroicons/vue/outline/CloudIcon'),
  'CloudDownloadIcon-outline': () => import('@heroicons/vue/outline/CloudDownloadIcon'),
  'CloudUploadIcon-outline': () => import('@heroicons/vue/outline/CloudUploadIcon'),
  'CodeIcon-outline': () => import('@heroicons/vue/outline/CodeIcon'),
  'CogIcon-outline': () => import('@heroicons/vue/outline/CogIcon'),
  'CollectionIcon-outline': () => import('@heroicons/vue/outline/CollectionIcon'),
  'ColorSwatchIcon-outline': () => import('@heroicons/vue/outline/ColorSwatchIcon'),
  'CreditCardIcon-outline': () => import('@heroicons/vue/outline/CreditCardIcon'),
  'CubeIcon-outline': () => import('@heroicons/vue/outline/CubeIcon'),
  'CubeTransparentIcon-outline': () => import('@heroicons/vue/outline/CubeTransparentIcon'),
  'CurrencyBangladeshiIcon-outline': () => import('@heroicons/vue/outline/CurrencyBangladeshiIcon'),
  'CurrencyDollarIcon-outline': () => import('@heroicons/vue/outline/CurrencyDollarIcon'),
  'CurrencyEuroIcon-outline': () => import('@heroicons/vue/outline/CurrencyEuroIcon'),
  'CurrencyPoundIcon-outline': () => import('@heroicons/vue/outline/CurrencyPoundIcon'),
  'CurrencyRupeeIcon-outline': () => import('@heroicons/vue/outline/CurrencyRupeeIcon'),
  'CurrencyYenIcon-outline': () => import('@heroicons/vue/outline/CurrencyYenIcon'),
  'CursorClickIcon-outline': () => import('@heroicons/vue/outline/CursorClickIcon'),
  'DatabaseIcon-outline': () => import('@heroicons/vue/outline/DatabaseIcon'),
  'DesktopComputerIcon-outline': () => import('@heroicons/vue/outline/DesktopComputerIcon'),
  'DeviceMobileIcon-outline': () => import('@heroicons/vue/outline/DeviceMobileIcon'),
  'DeviceTabletIcon-outline': () => import('@heroicons/vue/outline/DeviceTabletIcon'),
  'DocumentIcon-outline': () => import('@heroicons/vue/outline/DocumentIcon'),
  'DocumentAddIcon-outline': () => import('@heroicons/vue/outline/DocumentAddIcon'),
  'DocumentDownloadIcon-outline': () => import('@heroicons/vue/outline/DocumentDownloadIcon'),
  'DocumentDuplicateIcon-outline': () => import('@heroicons/vue/outline/DocumentDuplicateIcon'),
  'DocumentRemoveIcon-outline': () => import('@heroicons/vue/outline/DocumentRemoveIcon'),
  'DocumentReportIcon-outline': () => import('@heroicons/vue/outline/DocumentReportIcon'),
  'DocumentSearchIcon-outline': () => import('@heroicons/vue/outline/DocumentSearchIcon'),
  'DocumentTextIcon-outline': () => import('@heroicons/vue/outline/DocumentTextIcon'),
  'DotsCircleHorizontalIcon-outline': () => import('@heroicons/vue/outline/DotsCircleHorizontalIcon'),
  'DotsHorizontalIcon-outline': () => import('@heroicons/vue/outline/DotsHorizontalIcon'),
  'DotsVerticalIcon-outline': () => import('@heroicons/vue/outline/DotsVerticalIcon'),
  'DownloadIcon-outline': () => import('@heroicons/vue/outline/DownloadIcon'),
  'DuplicateIcon-outline': () => import('@heroicons/vue/outline/DuplicateIcon'),
  'EmojiHappyIcon-outline': () => import('@heroicons/vue/outline/EmojiHappyIcon'),
  'EmojiSadIcon-outline': () => import('@heroicons/vue/outline/EmojiSadIcon'),
  'ExclamationIcon-outline': () => import('@heroicons/vue/outline/ExclamationIcon'),
  'ExclamationCircleIcon-outline': () => import('@heroicons/vue/outline/ExclamationCircleIcon'),
  'ExternalLinkIcon-outline': () => import('@heroicons/vue/outline/ExternalLinkIcon'),
  'EyeIcon-outline': () => import('@heroicons/vue/outline/EyeIcon'),
  'EyeOffIcon-outline': () => import('@heroicons/vue/outline/EyeOffIcon'),
  'FastForwardIcon-outline': () => import('@heroicons/vue/outline/FastForwardIcon'),
  'FilmIcon-outline': () => import('@heroicons/vue/outline/FilmIcon'),
  'FilterIcon-outline': () => import('@heroicons/vue/outline/FilterIcon'),
  'FingerPrintIcon-outline': () => import('@heroicons/vue/outline/FingerPrintIcon'),
  'FireIcon-outline': () => import('@heroicons/vue/outline/FireIcon'),
  'FlagIcon-outline': () => import('@heroicons/vue/outline/FlagIcon'),
  'FolderIcon-outline': () => import('@heroicons/vue/outline/FolderIcon'),
  'FolderAddIcon-outline': () => import('@heroicons/vue/outline/FolderAddIcon'),
  'FolderDownloadIcon-outline': () => import('@heroicons/vue/outline/FolderDownloadIcon'),
  'FolderOpenIcon-outline': () => import('@heroicons/vue/outline/FolderOpenIcon'),
  'FolderRemoveIcon-outline': () => import('@heroicons/vue/outline/FolderRemoveIcon'),
  'GiftIcon-outline': () => import('@heroicons/vue/outline/GiftIcon'),
  'GlobeIcon-outline': () => import('@heroicons/vue/outline/GlobeIcon'),
  'GlobeAltIcon-outline': () => import('@heroicons/vue/outline/GlobeAltIcon'),
  'HandIcon-outline': () => import('@heroicons/vue/outline/HandIcon'),
  'HashtagIcon-outline': () => import('@heroicons/vue/outline/HashtagIcon'),
  'HeartIcon-outline': () => import('@heroicons/vue/outline/HeartIcon'),
  'HomeIcon-outline': () => import('@heroicons/vue/outline/HomeIcon'),
  'IdentificationIcon-outline': () => import('@heroicons/vue/outline/IdentificationIcon'),
  'InboxIcon-outline': () => import('@heroicons/vue/outline/InboxIcon'),
  'InboxInIcon-outline': () => import('@heroicons/vue/outline/InboxInIcon'),
  'InformationCircleIcon-outline': () => import('@heroicons/vue/outline/InformationCircleIcon'),
  'KeyIcon-outline': () => import('@heroicons/vue/outline/KeyIcon'),
  'LibraryIcon-outline': () => import('@heroicons/vue/outline/LibraryIcon'),
  'LightBulbIcon-outline': () => import('@heroicons/vue/outline/LightBulbIcon'),
  'LightningBoltIcon-outline': () => import('@heroicons/vue/outline/LightningBoltIcon'),
  'LinkIcon-outline': () => import('@heroicons/vue/outline/LinkIcon'),
  'LocationMarkerIcon-outline': () => import('@heroicons/vue/outline/LocationMarkerIcon'),
  'LockClosedIcon-outline': () => import('@heroicons/vue/outline/LockClosedIcon'),
  'LockOpenIcon-outline': () => import('@heroicons/vue/outline/LockOpenIcon'),
  'LoginIcon-outline': () => import('@heroicons/vue/outline/LoginIcon'),
  'LogoutIcon-outline': () => import('@heroicons/vue/outline/LogoutIcon'),
  'MailIcon-outline': () => import('@heroicons/vue/outline/MailIcon'),
  'MailOpenIcon-outline': () => import('@heroicons/vue/outline/MailOpenIcon'),
  'MapIcon-outline': () => import('@heroicons/vue/outline/MapIcon'),
  'MenuIcon-outline': () => import('@heroicons/vue/outline/MenuIcon'),
  'MenuAlt1Icon-outline': () => import('@heroicons/vue/outline/MenuAlt1Icon'),
  'MenuAlt2Icon-outline': () => import('@heroicons/vue/outline/MenuAlt2Icon'),
  'MenuAlt3Icon-outline': () => import('@heroicons/vue/outline/MenuAlt3Icon'),
  'MenuAlt4Icon-outline': () => import('@heroicons/vue/outline/MenuAlt4Icon'),
  'MicrophoneIcon-outline': () => import('@heroicons/vue/outline/MicrophoneIcon'),
  'MinusIcon-outline': () => import('@heroicons/vue/outline/MinusIcon'),
  'MinusCircleIcon-outline': () => import('@heroicons/vue/outline/MinusCircleIcon'),
  'MinusSmIcon-outline': () => import('@heroicons/vue/outline/MinusSmIcon'),
  'MoonIcon-outline': () => import('@heroicons/vue/outline/MoonIcon'),
  'MusicNoteIcon-outline': () => import('@heroicons/vue/outline/MusicNoteIcon'),
  'NewspaperIcon-outline': () => import('@heroicons/vue/outline/NewspaperIcon'),
  'OfficeBuildingIcon-outline': () => import('@heroicons/vue/outline/OfficeBuildingIcon'),
  'PaperAirplaneIcon-outline': () => import('@heroicons/vue/outline/PaperAirplaneIcon'),
  'PaperClipIcon-outline': () => import('@heroicons/vue/outline/PaperClipIcon'),
  'PauseIcon-outline': () => import('@heroicons/vue/outline/PauseIcon'),
  'PencilIcon-outline': () => import('@heroicons/vue/outline/PencilIcon'),
  'PencilAltIcon-outline': () => import('@heroicons/vue/outline/PencilAltIcon'),
  'PhoneIcon-outline': () => import('@heroicons/vue/outline/PhoneIcon'),
  'PhoneIncomingIcon-outline': () => import('@heroicons/vue/outline/PhoneIncomingIcon'),
  'PhoneMissedCallIcon-outline': () => import('@heroicons/vue/outline/PhoneMissedCallIcon'),
  'PhoneOutgoingIcon-outline': () => import('@heroicons/vue/outline/PhoneOutgoingIcon'),
  'PhotographIcon-outline': () => import('@heroicons/vue/outline/PhotographIcon'),
  'PlayIcon-outline': () => import('@heroicons/vue/outline/PlayIcon'),
  'PlusIcon-outline': () => import('@heroicons/vue/outline/PlusIcon'),
  'PlusCircleIcon-outline': () => import('@heroicons/vue/outline/PlusCircleIcon'),
  'PlusSmIcon-outline': () => import('@heroicons/vue/outline/PlusSmIcon'),
  'PresentationChartBarIcon-outline': () => import('@heroicons/vue/outline/PresentationChartBarIcon'),
  'PresentationChartLineIcon-outline': () => import('@heroicons/vue/outline/PresentationChartLineIcon'),
  'PrinterIcon-outline': () => import('@heroicons/vue/outline/PrinterIcon'),
  'PuzzleIcon-outline': () => import('@heroicons/vue/outline/PuzzleIcon'),
  'QrcodeIcon-outline': () => import('@heroicons/vue/outline/QrcodeIcon'),
  'QuestionMarkCircleIcon-outline': () => import('@heroicons/vue/outline/QuestionMarkCircleIcon'),
  'ReceiptRefundIcon-outline': () => import('@heroicons/vue/outline/ReceiptRefundIcon'),
  'ReceiptTaxIcon-outline': () => import('@heroicons/vue/outline/ReceiptTaxIcon'),
  'RefreshIcon-outline': () => import('@heroicons/vue/outline/RefreshIcon'),
  'ReplyIcon-outline': () => import('@heroicons/vue/outline/ReplyIcon'),
  'RewindIcon-outline': () => import('@heroicons/vue/outline/RewindIcon'),
  'RssIcon-outline': () => import('@heroicons/vue/outline/RssIcon'),
  'SaveIcon-outline': () => import('@heroicons/vue/outline/SaveIcon'),
  'SaveAsIcon-outline': () => import('@heroicons/vue/outline/SaveAsIcon'),
  'ScaleIcon-outline': () => import('@heroicons/vue/outline/ScaleIcon'),
  'ScissorsIcon-outline': () => import('@heroicons/vue/outline/ScissorsIcon'),
  'SearchIcon-outline': () => import('@heroicons/vue/outline/SearchIcon'),
  'SearchCircleIcon-outline': () => import('@heroicons/vue/outline/SearchCircleIcon'),
  'SelectorIcon-outline': () => import('@heroicons/vue/outline/SelectorIcon'),
  'ServerIcon-outline': () => import('@heroicons/vue/outline/ServerIcon'),
  'ShareIcon-outline': () => import('@heroicons/vue/outline/ShareIcon'),
  'ShieldCheckIcon-outline': () => import('@heroicons/vue/outline/ShieldCheckIcon'),
  'ShieldExclamationIcon-outline': () => import('@heroicons/vue/outline/ShieldExclamationIcon'),
  'ShoppingBagIcon-outline': () => import('@heroicons/vue/outline/ShoppingBagIcon'),
  'ShoppingCartIcon-outline': () => import('@heroicons/vue/outline/ShoppingCartIcon'),
  'SortAscendingIcon-outline': () => import('@heroicons/vue/outline/SortAscendingIcon'),
  'SortDescendingIcon-outline': () => import('@heroicons/vue/outline/SortDescendingIcon'),
  'SparklesIcon-outline': () => import('@heroicons/vue/outline/SparklesIcon'),
  'SpeakerphoneIcon-outline': () => import('@heroicons/vue/outline/SpeakerphoneIcon'),
  'StarIcon-outline': () => import('@heroicons/vue/outline/StarIcon'),
  'StatusOfflineIcon-outline': () => import('@heroicons/vue/outline/StatusOfflineIcon'),
  'StatusOnlineIcon-outline': () => import('@heroicons/vue/outline/StatusOnlineIcon'),
  'StopIcon-outline': () => import('@heroicons/vue/outline/StopIcon'),
  'SunIcon-outline': () => import('@heroicons/vue/outline/SunIcon'),
  'SupportIcon-outline': () => import('@heroicons/vue/outline/SupportIcon'),
  'SwitchHorizontalIcon-outline': () => import('@heroicons/vue/outline/SwitchHorizontalIcon'),
  'SwitchVerticalIcon-outline': () => import('@heroicons/vue/outline/SwitchVerticalIcon'),
  'TableIcon-outline': () => import('@heroicons/vue/outline/TableIcon'),
  'TagIcon-outline': () => import('@heroicons/vue/outline/TagIcon'),
  'TemplateIcon-outline': () => import('@heroicons/vue/outline/TemplateIcon'),
  'TerminalIcon-outline': () => import('@heroicons/vue/outline/TerminalIcon'),
  'ThumbDownIcon-outline': () => import('@heroicons/vue/outline/ThumbDownIcon'),
  'ThumbUpIcon-outline': () => import('@heroicons/vue/outline/ThumbUpIcon'),
  'TicketIcon-outline': () => import('@heroicons/vue/outline/TicketIcon'),
  'TranslateIcon-outline': () => import('@heroicons/vue/outline/TranslateIcon'),
  'TrashIcon-outline': () => import('@heroicons/vue/outline/TrashIcon'),
  'TrendingDownIcon-outline': () => import('@heroicons/vue/outline/TrendingDownIcon'),
  'TrendingUpIcon-outline': () => import('@heroicons/vue/outline/TrendingUpIcon'),
  'TruckIcon-outline': () => import('@heroicons/vue/outline/TruckIcon'),
  'UploadIcon-outline': () => import('@heroicons/vue/outline/UploadIcon'),
  'UserIcon-outline': () => import('@heroicons/vue/outline/UserIcon'),
  'UserAddIcon-outline': () => import('@heroicons/vue/outline/UserAddIcon'),
  'UserCircleIcon-outline': () => import('@heroicons/vue/outline/UserCircleIcon'),
  'UserGroupIcon-outline': () => import('@heroicons/vue/outline/UserGroupIcon'),
  'UserRemoveIcon-outline': () => import('@heroicons/vue/outline/UserRemoveIcon'),
  'UsersIcon-outline': () => import('@heroicons/vue/outline/UsersIcon'),
  'VariableIcon-outline': () => import('@heroicons/vue/outline/VariableIcon'),
  'VideoCameraIcon-outline': () => import('@heroicons/vue/outline/VideoCameraIcon'),
  'ViewBoardsIcon-outline': () => import('@heroicons/vue/outline/ViewBoardsIcon'),
  'ViewGridIcon-outline': () => import('@heroicons/vue/outline/ViewGridIcon'),
  'ViewGridAddIcon-outline': () => import('@heroicons/vue/outline/ViewGridAddIcon'),
  'ViewListIcon-outline': () => import('@heroicons/vue/outline/ViewListIcon'),
  'VolumeOffIcon-outline': () => import('@heroicons/vue/outline/VolumeOffIcon'),
  'VolumeUpIcon-outline': () => import('@heroicons/vue/outline/VolumeUpIcon'),
  'WifiIcon-outline': () => import('@heroicons/vue/outline/WifiIcon'),
  'XIcon-outline': () => import('@heroicons/vue/outline/XIcon'),
  'XCircleIcon-outline': () => import('@heroicons/vue/outline/XCircleIcon'),
  'ZoomInIcon-outline': () => import('@heroicons/vue/outline/ZoomInIcon'),
  'ZoomOutIcon-outline': () => import('@heroicons/vue/outline/ZoomOutIcon'),
  
  // Solid icons - 完整的 230 個圖標
  'AcademicCapIcon-solid': () => import('@heroicons/vue/solid/AcademicCapIcon'),
  'AdjustmentsIcon-solid': () => import('@heroicons/vue/solid/AdjustmentsIcon'),
  'AnnotationIcon-solid': () => import('@heroicons/vue/solid/AnnotationIcon'),
  'ArchiveIcon-solid': () => import('@heroicons/vue/solid/ArchiveIcon'),
  'ArrowCircleDownIcon-solid': () => import('@heroicons/vue/solid/ArrowCircleDownIcon'),
  'ArrowCircleLeftIcon-solid': () => import('@heroicons/vue/solid/ArrowCircleLeftIcon'),
  'ArrowCircleRightIcon-solid': () => import('@heroicons/vue/solid/ArrowCircleRightIcon'),
  'ArrowCircleUpIcon-solid': () => import('@heroicons/vue/solid/ArrowCircleUpIcon'),
  'ArrowDownIcon-solid': () => import('@heroicons/vue/solid/ArrowDownIcon'),
  'ArrowLeftIcon-solid': () => import('@heroicons/vue/solid/ArrowLeftIcon'),
  'ArrowNarrowDownIcon-solid': () => import('@heroicons/vue/solid/ArrowNarrowDownIcon'),
  'ArrowNarrowLeftIcon-solid': () => import('@heroicons/vue/solid/ArrowNarrowLeftIcon'),
  'ArrowNarrowRightIcon-solid': () => import('@heroicons/vue/solid/ArrowNarrowRightIcon'),
  'ArrowNarrowUpIcon-solid': () => import('@heroicons/vue/solid/ArrowNarrowUpIcon'),
  'ArrowRightIcon-solid': () => import('@heroicons/vue/solid/ArrowRightIcon'),
  'ArrowSmDownIcon-solid': () => import('@heroicons/vue/solid/ArrowSmDownIcon'),
  'ArrowSmLeftIcon-solid': () => import('@heroicons/vue/solid/ArrowSmLeftIcon'),
  'ArrowSmRightIcon-solid': () => import('@heroicons/vue/solid/ArrowSmRightIcon'),
  'ArrowSmUpIcon-solid': () => import('@heroicons/vue/solid/ArrowSmUpIcon'),
  'ArrowUpIcon-solid': () => import('@heroicons/vue/solid/ArrowUpIcon'),
  'ArrowsExpandIcon-solid': () => import('@heroicons/vue/solid/ArrowsExpandIcon'),
  'AtSymbolIcon-solid': () => import('@heroicons/vue/solid/AtSymbolIcon'),
  'BackspaceIcon-solid': () => import('@heroicons/vue/solid/BackspaceIcon'),
  'BadgeCheckIcon-solid': () => import('@heroicons/vue/solid/BadgeCheckIcon'),
  'BanIcon-solid': () => import('@heroicons/vue/solid/BanIcon'),
  'BeakerIcon-solid': () => import('@heroicons/vue/solid/BeakerIcon'),
  'BellIcon-solid': () => import('@heroicons/vue/solid/BellIcon'),
  'BookOpenIcon-solid': () => import('@heroicons/vue/solid/BookOpenIcon'),
  'BookmarkIcon-solid': () => import('@heroicons/vue/solid/BookmarkIcon'),
  'BookmarkAltIcon-solid': () => import('@heroicons/vue/solid/BookmarkAltIcon'),
  'BriefcaseIcon-solid': () => import('@heroicons/vue/solid/BriefcaseIcon'),
  'CakeIcon-solid': () => import('@heroicons/vue/solid/CakeIcon'),
  'CalculatorIcon-solid': () => import('@heroicons/vue/solid/CalculatorIcon'),
  'CalendarIcon-solid': () => import('@heroicons/vue/solid/CalendarIcon'),
  'CameraIcon-solid': () => import('@heroicons/vue/solid/CameraIcon'),
  'CashIcon-solid': () => import('@heroicons/vue/solid/CashIcon'),
  'ChartBarIcon-solid': () => import('@heroicons/vue/solid/ChartBarIcon'),
  'ChartPieIcon-solid': () => import('@heroicons/vue/solid/ChartPieIcon'),
  'ChartSquareBarIcon-solid': () => import('@heroicons/vue/solid/ChartSquareBarIcon'),
  'ChatIcon-solid': () => import('@heroicons/vue/solid/ChatIcon'),
  'ChatAltIcon-solid': () => import('@heroicons/vue/solid/ChatAltIcon'),
  'ChatAlt2Icon-solid': () => import('@heroicons/vue/solid/ChatAlt2Icon'),
  'CheckIcon-solid': () => import('@heroicons/vue/solid/CheckIcon'),
  'CheckCircleIcon-solid': () => import('@heroicons/vue/solid/CheckCircleIcon'),
  'ChevronDoubleDownIcon-solid': () => import('@heroicons/vue/solid/ChevronDoubleDownIcon'),
  'ChevronDoubleLeftIcon-solid': () => import('@heroicons/vue/solid/ChevronDoubleLeftIcon'),
  'ChevronDoubleRightIcon-solid': () => import('@heroicons/vue/solid/ChevronDoubleRightIcon'),
  'ChevronDoubleUpIcon-solid': () => import('@heroicons/vue/solid/ChevronDoubleUpIcon'),
  'ChevronDownIcon-solid': () => import('@heroicons/vue/solid/ChevronDownIcon'),
  'ChevronLeftIcon-solid': () => import('@heroicons/vue/solid/ChevronLeftIcon'),
  'ChevronRightIcon-solid': () => import('@heroicons/vue/solid/ChevronRightIcon'),
  'ChevronUpIcon-solid': () => import('@heroicons/vue/solid/ChevronUpIcon'),
  'ChipIcon-solid': () => import('@heroicons/vue/solid/ChipIcon'),
  'ClipboardIcon-solid': () => import('@heroicons/vue/solid/ClipboardIcon'),
  'ClipboardCheckIcon-solid': () => import('@heroicons/vue/solid/ClipboardCheckIcon'),
  'ClipboardCopyIcon-solid': () => import('@heroicons/vue/solid/ClipboardCopyIcon'),
  'ClipboardListIcon-solid': () => import('@heroicons/vue/solid/ClipboardListIcon'),
  'ClockIcon-solid': () => import('@heroicons/vue/solid/ClockIcon'),
  'CloudIcon-solid': () => import('@heroicons/vue/solid/CloudIcon'),
  'CloudDownloadIcon-solid': () => import('@heroicons/vue/solid/CloudDownloadIcon'),
  'CloudUploadIcon-solid': () => import('@heroicons/vue/solid/CloudUploadIcon'),
  'CodeIcon-solid': () => import('@heroicons/vue/solid/CodeIcon'),
  'CogIcon-solid': () => import('@heroicons/vue/solid/CogIcon'),
  'CollectionIcon-solid': () => import('@heroicons/vue/solid/CollectionIcon'),
  'ColorSwatchIcon-solid': () => import('@heroicons/vue/solid/ColorSwatchIcon'),
  'CreditCardIcon-solid': () => import('@heroicons/vue/solid/CreditCardIcon'),
  'CubeIcon-solid': () => import('@heroicons/vue/solid/CubeIcon'),
  'CubeTransparentIcon-solid': () => import('@heroicons/vue/solid/CubeTransparentIcon'),
  'CurrencyBangladeshiIcon-solid': () => import('@heroicons/vue/solid/CurrencyBangladeshiIcon'),
  'CurrencyDollarIcon-solid': () => import('@heroicons/vue/solid/CurrencyDollarIcon'),
  'CurrencyEuroIcon-solid': () => import('@heroicons/vue/solid/CurrencyEuroIcon'),
  'CurrencyPoundIcon-solid': () => import('@heroicons/vue/solid/CurrencyPoundIcon'),
  'CurrencyRupeeIcon-solid': () => import('@heroicons/vue/solid/CurrencyRupeeIcon'),
  'CurrencyYenIcon-solid': () => import('@heroicons/vue/solid/CurrencyYenIcon'),
  'CursorClickIcon-solid': () => import('@heroicons/vue/solid/CursorClickIcon'),
  'DatabaseIcon-solid': () => import('@heroicons/vue/solid/DatabaseIcon'),
  'DesktopComputerIcon-solid': () => import('@heroicons/vue/solid/DesktopComputerIcon'),
  'DeviceMobileIcon-solid': () => import('@heroicons/vue/solid/DeviceMobileIcon'),
  'DeviceTabletIcon-solid': () => import('@heroicons/vue/solid/DeviceTabletIcon'),
  'DocumentIcon-solid': () => import('@heroicons/vue/solid/DocumentIcon'),
  'DocumentAddIcon-solid': () => import('@heroicons/vue/solid/DocumentAddIcon'),
  'DocumentDownloadIcon-solid': () => import('@heroicons/vue/solid/DocumentDownloadIcon'),
  'DocumentDuplicateIcon-solid': () => import('@heroicons/vue/solid/DocumentDuplicateIcon'),
  'DocumentRemoveIcon-solid': () => import('@heroicons/vue/solid/DocumentRemoveIcon'),
  'DocumentReportIcon-solid': () => import('@heroicons/vue/solid/DocumentReportIcon'),
  'DocumentSearchIcon-solid': () => import('@heroicons/vue/solid/DocumentSearchIcon'),
  'DocumentTextIcon-solid': () => import('@heroicons/vue/solid/DocumentTextIcon'),
  'DotsCircleHorizontalIcon-solid': () => import('@heroicons/vue/solid/DotsCircleHorizontalIcon'),
  'DotsHorizontalIcon-solid': () => import('@heroicons/vue/solid/DotsHorizontalIcon'),
  'DotsVerticalIcon-solid': () => import('@heroicons/vue/solid/DotsVerticalIcon'),
  'DownloadIcon-solid': () => import('@heroicons/vue/solid/DownloadIcon'),
  'DuplicateIcon-solid': () => import('@heroicons/vue/solid/DuplicateIcon'),
  'EmojiHappyIcon-solid': () => import('@heroicons/vue/solid/EmojiHappyIcon'),
  'EmojiSadIcon-solid': () => import('@heroicons/vue/solid/EmojiSadIcon'),
  'ExclamationIcon-solid': () => import('@heroicons/vue/solid/ExclamationIcon'),
  'ExclamationCircleIcon-solid': () => import('@heroicons/vue/solid/ExclamationCircleIcon'),
  'ExternalLinkIcon-solid': () => import('@heroicons/vue/solid/ExternalLinkIcon'),
  'EyeIcon-solid': () => import('@heroicons/vue/solid/EyeIcon'),
  'EyeOffIcon-solid': () => import('@heroicons/vue/solid/EyeOffIcon'),
  'FastForwardIcon-solid': () => import('@heroicons/vue/solid/FastForwardIcon'),
  'FilmIcon-solid': () => import('@heroicons/vue/solid/FilmIcon'),
  'FilterIcon-solid': () => import('@heroicons/vue/solid/FilterIcon'),
  'FingerPrintIcon-solid': () => import('@heroicons/vue/solid/FingerPrintIcon'),
  'FireIcon-solid': () => import('@heroicons/vue/solid/FireIcon'),
  'FlagIcon-solid': () => import('@heroicons/vue/solid/FlagIcon'),
  'FolderIcon-solid': () => import('@heroicons/vue/solid/FolderIcon'),
  'FolderAddIcon-solid': () => import('@heroicons/vue/solid/FolderAddIcon'),
  'FolderDownloadIcon-solid': () => import('@heroicons/vue/solid/FolderDownloadIcon'),
  'FolderOpenIcon-solid': () => import('@heroicons/vue/solid/FolderOpenIcon'),
  'FolderRemoveIcon-solid': () => import('@heroicons/vue/solid/FolderRemoveIcon'),
  'GiftIcon-solid': () => import('@heroicons/vue/solid/GiftIcon'),
  'GlobeIcon-solid': () => import('@heroicons/vue/solid/GlobeIcon'),
  'GlobeAltIcon-solid': () => import('@heroicons/vue/solid/GlobeAltIcon'),
  'HandIcon-solid': () => import('@heroicons/vue/solid/HandIcon'),
  'HashtagIcon-solid': () => import('@heroicons/vue/solid/HashtagIcon'),
  'HeartIcon-solid': () => import('@heroicons/vue/solid/HeartIcon'),
  'HomeIcon-solid': () => import('@heroicons/vue/solid/HomeIcon'),
  'IdentificationIcon-solid': () => import('@heroicons/vue/solid/IdentificationIcon'),
  'InboxIcon-solid': () => import('@heroicons/vue/solid/InboxIcon'),
  'InboxInIcon-solid': () => import('@heroicons/vue/solid/InboxInIcon'),
  'InformationCircleIcon-solid': () => import('@heroicons/vue/solid/InformationCircleIcon'),
  'KeyIcon-solid': () => import('@heroicons/vue/solid/KeyIcon'),
  'LibraryIcon-solid': () => import('@heroicons/vue/solid/LibraryIcon'),
  'LightBulbIcon-solid': () => import('@heroicons/vue/solid/LightBulbIcon'),
  'LightningBoltIcon-solid': () => import('@heroicons/vue/solid/LightningBoltIcon'),
  'LinkIcon-solid': () => import('@heroicons/vue/solid/LinkIcon'),
  'LocationMarkerIcon-solid': () => import('@heroicons/vue/solid/LocationMarkerIcon'),
  'LockClosedIcon-solid': () => import('@heroicons/vue/solid/LockClosedIcon'),
  'LockOpenIcon-solid': () => import('@heroicons/vue/solid/LockOpenIcon'),
  'LoginIcon-solid': () => import('@heroicons/vue/solid/LoginIcon'),
  'LogoutIcon-solid': () => import('@heroicons/vue/solid/LogoutIcon'),
  'MailIcon-solid': () => import('@heroicons/vue/solid/MailIcon'),
  'MailOpenIcon-solid': () => import('@heroicons/vue/solid/MailOpenIcon'),
  'MapIcon-solid': () => import('@heroicons/vue/solid/MapIcon'),
  'MenuIcon-solid': () => import('@heroicons/vue/solid/MenuIcon'),
  'MenuAlt1Icon-solid': () => import('@heroicons/vue/solid/MenuAlt1Icon'),
  'MenuAlt2Icon-solid': () => import('@heroicons/vue/solid/MenuAlt2Icon'),
  'MenuAlt3Icon-solid': () => import('@heroicons/vue/solid/MenuAlt3Icon'),
  'MenuAlt4Icon-solid': () => import('@heroicons/vue/solid/MenuAlt4Icon'),
  'MicrophoneIcon-solid': () => import('@heroicons/vue/solid/MicrophoneIcon'),
  'MinusIcon-solid': () => import('@heroicons/vue/solid/MinusIcon'),
  'MinusCircleIcon-solid': () => import('@heroicons/vue/solid/MinusCircleIcon'),
  'MinusSmIcon-solid': () => import('@heroicons/vue/solid/MinusSmIcon'),
  'MoonIcon-solid': () => import('@heroicons/vue/solid/MoonIcon'),
  'MusicNoteIcon-solid': () => import('@heroicons/vue/solid/MusicNoteIcon'),
  'NewspaperIcon-solid': () => import('@heroicons/vue/solid/NewspaperIcon'),
  'OfficeBuildingIcon-solid': () => import('@heroicons/vue/solid/OfficeBuildingIcon'),
  'PaperAirplaneIcon-solid': () => import('@heroicons/vue/solid/PaperAirplaneIcon'),
  'PaperClipIcon-solid': () => import('@heroicons/vue/solid/PaperClipIcon'),
  'PauseIcon-solid': () => import('@heroicons/vue/solid/PauseIcon'),
  'PencilIcon-solid': () => import('@heroicons/vue/solid/PencilIcon'),
  'PencilAltIcon-solid': () => import('@heroicons/vue/solid/PencilAltIcon'),
  'PhoneIcon-solid': () => import('@heroicons/vue/solid/PhoneIcon'),
  'PhoneIncomingIcon-solid': () => import('@heroicons/vue/solid/PhoneIncomingIcon'),
  'PhoneMissedCallIcon-solid': () => import('@heroicons/vue/solid/PhoneMissedCallIcon'),
  'PhoneOutgoingIcon-solid': () => import('@heroicons/vue/solid/PhoneOutgoingIcon'),
  'PhotographIcon-solid': () => import('@heroicons/vue/solid/PhotographIcon'),
  'PlayIcon-solid': () => import('@heroicons/vue/solid/PlayIcon'),
  'PlusIcon-solid': () => import('@heroicons/vue/solid/PlusIcon'),
  'PlusCircleIcon-solid': () => import('@heroicons/vue/solid/PlusCircleIcon'),
  'PlusSmIcon-solid': () => import('@heroicons/vue/solid/PlusSmIcon'),
  'PresentationChartBarIcon-solid': () => import('@heroicons/vue/solid/PresentationChartBarIcon'),
  'PresentationChartLineIcon-solid': () => import('@heroicons/vue/solid/PresentationChartLineIcon'),
  'PrinterIcon-solid': () => import('@heroicons/vue/solid/PrinterIcon'),
  'PuzzleIcon-solid': () => import('@heroicons/vue/solid/PuzzleIcon'),
  'QrcodeIcon-solid': () => import('@heroicons/vue/solid/QrcodeIcon'),
  'QuestionMarkCircleIcon-solid': () => import('@heroicons/vue/solid/QuestionMarkCircleIcon'),
  'ReceiptRefundIcon-solid': () => import('@heroicons/vue/solid/ReceiptRefundIcon'),
  'ReceiptTaxIcon-solid': () => import('@heroicons/vue/solid/ReceiptTaxIcon'),
  'RefreshIcon-solid': () => import('@heroicons/vue/solid/RefreshIcon'),
  'ReplyIcon-solid': () => import('@heroicons/vue/solid/ReplyIcon'),
  'RewindIcon-solid': () => import('@heroicons/vue/solid/RewindIcon'),
  'RssIcon-solid': () => import('@heroicons/vue/solid/RssIcon'),
  'SaveIcon-solid': () => import('@heroicons/vue/solid/SaveIcon'),
  'SaveAsIcon-solid': () => import('@heroicons/vue/solid/SaveAsIcon'),
  'ScaleIcon-solid': () => import('@heroicons/vue/solid/ScaleIcon'),
  'ScissorsIcon-solid': () => import('@heroicons/vue/solid/ScissorsIcon'),
  'SearchIcon-solid': () => import('@heroicons/vue/solid/SearchIcon'),
  'SearchCircleIcon-solid': () => import('@heroicons/vue/solid/SearchCircleIcon'),
  'SelectorIcon-solid': () => import('@heroicons/vue/solid/SelectorIcon'),
  'ServerIcon-solid': () => import('@heroicons/vue/solid/ServerIcon'),
  'ShareIcon-solid': () => import('@heroicons/vue/solid/ShareIcon'),
  'ShieldCheckIcon-solid': () => import('@heroicons/vue/solid/ShieldCheckIcon'),
  'ShieldExclamationIcon-solid': () => import('@heroicons/vue/solid/ShieldExclamationIcon'),
  'ShoppingBagIcon-solid': () => import('@heroicons/vue/solid/ShoppingBagIcon'),
  'ShoppingCartIcon-solid': () => import('@heroicons/vue/solid/ShoppingCartIcon'),
  'SortAscendingIcon-solid': () => import('@heroicons/vue/solid/SortAscendingIcon'),
  'SortDescendingIcon-solid': () => import('@heroicons/vue/solid/SortDescendingIcon'),
  'SparklesIcon-solid': () => import('@heroicons/vue/solid/SparklesIcon'),
  'SpeakerphoneIcon-solid': () => import('@heroicons/vue/solid/SpeakerphoneIcon'),
  'StarIcon-solid': () => import('@heroicons/vue/solid/StarIcon'),
  'StatusOfflineIcon-solid': () => import('@heroicons/vue/solid/StatusOfflineIcon'),
  'StatusOnlineIcon-solid': () => import('@heroicons/vue/solid/StatusOnlineIcon'),
  'StopIcon-solid': () => import('@heroicons/vue/solid/StopIcon'),
  'SunIcon-solid': () => import('@heroicons/vue/solid/SunIcon'),
  'SupportIcon-solid': () => import('@heroicons/vue/solid/SupportIcon'),
  'SwitchHorizontalIcon-solid': () => import('@heroicons/vue/solid/SwitchHorizontalIcon'),
  'SwitchVerticalIcon-solid': () => import('@heroicons/vue/solid/SwitchVerticalIcon'),
  'TableIcon-solid': () => import('@heroicons/vue/solid/TableIcon'),
  'TagIcon-solid': () => import('@heroicons/vue/solid/TagIcon'),
  'TemplateIcon-solid': () => import('@heroicons/vue/solid/TemplateIcon'),
  'TerminalIcon-solid': () => import('@heroicons/vue/solid/TerminalIcon'),
  'ThumbDownIcon-solid': () => import('@heroicons/vue/solid/ThumbDownIcon'),
  'ThumbUpIcon-solid': () => import('@heroicons/vue/solid/ThumbUpIcon'),
  'TicketIcon-solid': () => import('@heroicons/vue/solid/TicketIcon'),
  'TranslateIcon-solid': () => import('@heroicons/vue/solid/TranslateIcon'),
  'TrashIcon-solid': () => import('@heroicons/vue/solid/TrashIcon'),
  'TrendingDownIcon-solid': () => import('@heroicons/vue/solid/TrendingDownIcon'),
  'TrendingUpIcon-solid': () => import('@heroicons/vue/solid/TrendingUpIcon'),
  'TruckIcon-solid': () => import('@heroicons/vue/solid/TruckIcon'),
  'UploadIcon-solid': () => import('@heroicons/vue/solid/UploadIcon'),
  'UserIcon-solid': () => import('@heroicons/vue/solid/UserIcon'),
  'UserAddIcon-solid': () => import('@heroicons/vue/solid/UserAddIcon'),
  'UserCircleIcon-solid': () => import('@heroicons/vue/solid/UserCircleIcon'),
  'UserGroupIcon-solid': () => import('@heroicons/vue/solid/UserGroupIcon'),
  'UserRemoveIcon-solid': () => import('@heroicons/vue/solid/UserRemoveIcon'),
  'UsersIcon-solid': () => import('@heroicons/vue/solid/UsersIcon'),
  'VariableIcon-solid': () => import('@heroicons/vue/solid/VariableIcon'),
  'VideoCameraIcon-solid': () => import('@heroicons/vue/solid/VideoCameraIcon'),
  'ViewBoardsIcon-solid': () => import('@heroicons/vue/solid/ViewBoardsIcon'),
  'ViewGridIcon-solid': () => import('@heroicons/vue/solid/ViewGridIcon'),
  'ViewGridAddIcon-solid': () => import('@heroicons/vue/solid/ViewGridAddIcon'),
  'ViewListIcon-solid': () => import('@heroicons/vue/solid/ViewListIcon'),
  'VolumeOffIcon-solid': () => import('@heroicons/vue/solid/VolumeOffIcon'),
  'VolumeUpIcon-solid': () => import('@heroicons/vue/solid/VolumeUpIcon'),
  'WifiIcon-solid': () => import('@heroicons/vue/solid/WifiIcon'),
  'XIcon-solid': () => import('@heroicons/vue/solid/XIcon'),
  'XCircleIcon-solid': () => import('@heroicons/vue/solid/XCircleIcon'),
  'ZoomInIcon-solid': () => import('@heroicons/vue/solid/ZoomInIcon'),
  'ZoomOutIcon-solid': () => import('@heroicons/vue/solid/ZoomOutIcon'),
}

/**
 * 載入指定的 Heroicon
 * @param {string} iconName - 圖標名稱 (如: 'HomeIcon')
 * @param {string} variant - 圖標變體 ('outline' | 'solid')
 * @returns {Promise<Component|null>} 返回 Vue 組件或 null
 */
export const loadHeroicon = async (iconName, variant = 'outline') => {
  try {
    const iconKey = `${iconName}-${variant}`
    const loader = heroiconsLoaders[iconKey]
    
    if (loader) {
      const iconModule = await loader()
      return iconModule.default
    } else {
      console.warn(`Hero icon not found in loader: ${iconKey}`)
      return null
    }
  } catch (error) {
    console.error(`Failed to load hero icon: ${iconName}-${variant}`, error)
    return null
  }
}

/**
 * 檢查指定的 Heroicon 是否可用
 * @param {string} iconName - 圖標名稱
 * @param {string} variant - 圖標變體
 * @returns {boolean} 是否可用
 */
export const isHeroiconAvailable = (iconName, variant = 'outline') => {
  const iconKey = `${iconName}-${variant}`
  return iconKey in heroiconsLoaders
}

/**
 * 取得所有可用的 Heroicon 名稱
 * @param {string} variant - 圖標變體 ('outline' | 'solid' | null)
 * @returns {string[]} 圖標名稱陣列
 */
export const getAvailableHeroicons = (variant = null) => {
  const keys = Object.keys(heroiconsLoaders)
  
  if (variant) {
    return keys
      .filter(key => key.endsWith(`-${variant}`))
      .map(key => key.replace(`-${variant}`, ''))
  }
  
  // 返回所有唯一的圖標名稱
  const iconNames = new Set()
  keys.forEach(key => {
    const iconName = key.replace(/-(outline|solid)$/, '')
    iconNames.add(iconName)
  })
  
  return Array.from(iconNames)
}

/**
 * 檢查圖標名稱是否存在於 allHeroicons.js 清單中
 * @param {string} iconName - 圖標名稱
 * @returns {boolean} 是否存在於清單中
 */
export const isHeroiconInList = (iconName) => {
  return heroiconsOutline.some(icon => icon.component === iconName)
}

// 預設導出
export default {
  loadHeroicon,
  isHeroiconAvailable,
  getAvailableHeroicons,
  isHeroiconInList,
  heroiconsLoaders
}