<?php

/**
 * Bootstrap Icons 完整配置
 * 
 * 從前端 JS 檔案轉換的完整 Bootstrap Icons 清單
 * 包含分類資訊和關鍵字，支援後端 API 使用
 */

return [
    /**
     * 分類資訊對應表
     * 
     * 從前端 categoryMap 轉換，包含中文名稱和優先級
     */
    'categories' => [
        'general' => [
            'name' => '通用圖標',
            'description' => '最常用的基礎圖標',
            'priority' => 'immediate',
        ],
        'ui' => [
            'name' => 'UI 介面', 
            'description' => '使用者介面元件與控制項',
            'priority' => 'high',
        ],
        'communications' => [
            'name' => '通訊溝通',
            'description' => '郵件、電話、聊天等通訊圖標', 
            'priority' => 'high',
        ],
        'files' => [
            'name' => '檔案文件',
            'description' => '檔案、資料夾、文件類型相關圖標',
            'priority' => 'medium',
        ],
        'media' => [
            'name' => '媒體播放',
            'description' => '播放、音量、錄製等媒體控制圖標',
            'priority' => 'medium',
        ],
        'people' => [
            'name' => '人物相關', 
            'description' => '人員、群組、身體部位相關圖標',
            'priority' => 'medium',
        ],
        'alphanumeric' => [
            'name' => '數字字母',
            'description' => '數字、字母、文字排版相關圖標',
            'priority' => 'low',
        ],
        'others' => [
            'name' => '其他圖標',
            'description' => '商業、地理、工具、天氣等其他圖標',
            'priority' => 'low',
        ],
    ],
    
    /**
     * 圖標資料（按分類組織）
     * 
     * 每個圖標包含：
     * - name: 顯示名稱
     * - class: Bootstrap Icons CSS 類別
     * - category: 所屬分類
     * - keywords: 搜尋關鍵字陣列
     */
    'icons' => [
        'general' => [
            ['name' => 'House', 'class' => 'bi-house', 'category' => 'general', 'keywords' => ['house', 'home', 'building', 'main', 'dashboard']],
            ['name' => 'House Door', 'class' => 'bi-house-door', 'category' => 'general', 'keywords' => ['house', 'door', 'home', 'entrance', 'entry']],
            ['name' => 'House Door Fill', 'class' => 'bi-house-door-fill', 'category' => 'general', 'keywords' => ['house', 'door', 'fill', 'home', 'entrance']],
            ['name' => 'House Fill', 'class' => 'bi-house-fill', 'category' => 'general', 'keywords' => ['house', 'fill', 'home', 'building']],
            ['name' => 'Search', 'class' => 'bi-search', 'category' => 'general', 'keywords' => ['search', 'find', 'look', 'magnify', 'query']],
            ['name' => 'Search Heart', 'class' => 'bi-search-heart', 'category' => 'general', 'keywords' => ['search', 'heart', 'love', 'find', 'favorite']],
            ['name' => 'Search Heart Fill', 'class' => 'bi-search-heart-fill', 'category' => 'general', 'keywords' => ['search', 'heart', 'fill', 'love', 'favorite']],
            ['name' => 'Gear', 'class' => 'bi-gear', 'category' => 'general', 'keywords' => ['gear', 'settings', 'configuration', 'options', 'preferences']],
            ['name' => 'Gear Fill', 'class' => 'bi-gear-fill', 'category' => 'general', 'keywords' => ['gear', 'fill', 'settings', 'configuration']],
            ['name' => 'Gear Wide', 'class' => 'bi-gear-wide', 'category' => 'general', 'keywords' => ['gear', 'wide', 'settings', 'configuration']],
            ['name' => 'Gear Wide Connected', 'class' => 'bi-gear-wide-connected', 'category' => 'general', 'keywords' => ['gear', 'wide', 'connected', 'settings']],
            ['name' => 'Bell', 'class' => 'bi-bell', 'category' => 'general', 'keywords' => ['bell', 'notification', 'alert', 'ring', 'sound']],
            ['name' => 'Bell Fill', 'class' => 'bi-bell-fill', 'category' => 'general', 'keywords' => ['bell', 'fill', 'notification', 'alert']],
            ['name' => 'Bell Slash', 'class' => 'bi-bell-slash', 'category' => 'general', 'keywords' => ['bell', 'slash', 'mute', 'notification', 'silent']],
            ['name' => 'Bell Slash Fill', 'class' => 'bi-bell-slash-fill', 'category' => 'general', 'keywords' => ['bell', 'slash', 'fill', 'mute', 'silent']],
            ['name' => 'Bookmark', 'class' => 'bi-bookmark', 'category' => 'general', 'keywords' => ['bookmark', 'save', 'favorite', 'mark', 'remember']],
            ['name' => 'Bookmark Fill', 'class' => 'bi-bookmark-fill', 'category' => 'general', 'keywords' => ['bookmark', 'fill', 'save', 'favorite']],
            ['name' => 'Bookmark Star', 'class' => 'bi-bookmark-star', 'category' => 'general', 'keywords' => ['bookmark', 'star', 'favorite', 'special']],
            ['name' => 'Bookmark Star Fill', 'class' => 'bi-bookmark-star-fill', 'category' => 'general', 'keywords' => ['bookmark', 'star', 'fill', 'favorite']],
            ['name' => 'Calendar', 'class' => 'bi-calendar', 'category' => 'general', 'keywords' => ['calendar', 'date', 'time', 'schedule', 'appointment']],
            ['name' => 'Calendar Fill', 'class' => 'bi-calendar-fill', 'category' => 'general', 'keywords' => ['calendar', 'fill', 'date', 'schedule']],
            ['name' => 'Calendar Check', 'class' => 'bi-calendar-check', 'category' => 'general', 'keywords' => ['calendar', 'check', 'done', 'completed', 'appointment']],
            ['name' => 'Calendar Check Fill', 'class' => 'bi-calendar-check-fill', 'category' => 'general', 'keywords' => ['calendar', 'check', 'fill', 'done']],
            ['name' => 'Clock', 'class' => 'bi-clock', 'category' => 'general', 'keywords' => ['clock', 'time', 'hour', 'minute', 'schedule']],
            ['name' => 'Clock Fill', 'class' => 'bi-clock-fill', 'category' => 'general', 'keywords' => ['clock', 'fill', 'time', 'hour']],
            ['name' => 'Clock History', 'class' => 'bi-clock-history', 'category' => 'general', 'keywords' => ['clock', 'history', 'time', 'past', 'previous']],
            ['name' => 'Alarm', 'class' => 'bi-alarm', 'category' => 'general', 'keywords' => ['alarm', 'wake', 'ring', 'alert', 'timer']],
            ['name' => 'Alarm Fill', 'class' => 'bi-alarm-fill', 'category' => 'general', 'keywords' => ['alarm', 'fill', 'wake', 'ring']],
            ['name' => 'Stopwatch', 'class' => 'bi-stopwatch', 'category' => 'general', 'keywords' => ['stopwatch', 'timer', 'measure', 'time', 'chronometer']],
            ['name' => 'Stopwatch Fill', 'class' => 'bi-stopwatch-fill', 'category' => 'general', 'keywords' => ['stopwatch', 'fill', 'timer', 'measure']],
            ['name' => 'Heart', 'class' => 'bi-heart', 'category' => 'general', 'keywords' => ['heart', 'love', 'like', 'favorite', 'romance']],
            ['name' => 'Heart Fill', 'class' => 'bi-heart-fill', 'category' => 'general', 'keywords' => ['heart', 'fill', 'love', 'like']],
            ['name' => 'Heart Half', 'class' => 'bi-heart-half', 'category' => 'general', 'keywords' => ['heart', 'half', 'partial', 'love']],
            ['name' => 'Star', 'class' => 'bi-star', 'category' => 'general', 'keywords' => ['star', 'favorite', 'rating', 'bookmark', 'quality']],
            ['name' => 'Star Fill', 'class' => 'bi-star-fill', 'category' => 'general', 'keywords' => ['star', 'fill', 'favorite', 'rating']],
            ['name' => 'Star Half', 'class' => 'bi-star-half', 'category' => 'general', 'keywords' => ['star', 'half', 'rating', 'partial']],
            ['name' => 'Award', 'class' => 'bi-award', 'category' => 'general', 'keywords' => ['award', 'medal', 'prize', 'winner', 'achievement']],
            ['name' => 'Award Fill', 'class' => 'bi-award-fill', 'category' => 'general', 'keywords' => ['award', 'fill', 'medal', 'prize']],
            ['name' => 'Trophy', 'class' => 'bi-trophy', 'category' => 'general', 'keywords' => ['trophy', 'winner', 'champion', 'award', 'prize']],
            ['name' => 'Trophy Fill', 'class' => 'bi-trophy-fill', 'category' => 'general', 'keywords' => ['trophy', 'fill', 'winner', 'champion']],
            ['name' => 'Gift', 'class' => 'bi-gift', 'category' => 'general', 'keywords' => ['gift', 'present', 'box', 'surprise', 'reward']],
            ['name' => 'Gift Fill', 'class' => 'bi-gift-fill', 'category' => 'general', 'keywords' => ['gift', 'fill', 'present', 'box']],
        ],
        
        'ui' => [
            ['name' => 'Arrow Up', 'class' => 'bi-arrow-up', 'category' => 'ui', 'keywords' => ['arrow', 'up', 'direction', 'navigation', 'top']],
            ['name' => 'Arrow Down', 'class' => 'bi-arrow-down', 'category' => 'ui', 'keywords' => ['arrow', 'down', 'direction', 'navigation', 'bottom']],
            ['name' => 'Arrow Left', 'class' => 'bi-arrow-left', 'category' => 'ui', 'keywords' => ['arrow', 'left', 'direction', 'navigation', 'back']],
            ['name' => 'Arrow Right', 'class' => 'bi-arrow-right', 'category' => 'ui', 'keywords' => ['arrow', 'right', 'direction', 'navigation', 'forward']],
            ['name' => 'Chevron Up', 'class' => 'bi-chevron-up', 'category' => 'ui', 'keywords' => ['chevron', 'up', 'expand', 'direction', 'arrow']],
            ['name' => 'Chevron Down', 'class' => 'bi-chevron-down', 'category' => 'ui', 'keywords' => ['chevron', 'down', 'collapse', 'direction', 'arrow']],
            ['name' => 'Chevron Left', 'class' => 'bi-chevron-left', 'category' => 'ui', 'keywords' => ['chevron', 'left', 'direction', 'arrow', 'back']],
            ['name' => 'Chevron Right', 'class' => 'bi-chevron-right', 'category' => 'ui', 'keywords' => ['chevron', 'right', 'direction', 'arrow', 'forward']],
            ['name' => 'Plus', 'class' => 'bi-plus', 'category' => 'ui', 'keywords' => ['plus', 'add', 'create', 'new', 'increase']],
            ['name' => 'Plus Circle', 'class' => 'bi-plus-circle', 'category' => 'ui', 'keywords' => ['plus', 'circle', 'add', 'create']],
            ['name' => 'Plus Circle Fill', 'class' => 'bi-plus-circle-fill', 'category' => 'ui', 'keywords' => ['plus', 'circle', 'fill', 'add']],
            ['name' => 'Plus Square', 'class' => 'bi-plus-square', 'category' => 'ui', 'keywords' => ['plus', 'square', 'add', 'create']],
            ['name' => 'Plus Square Fill', 'class' => 'bi-plus-square-fill', 'category' => 'ui', 'keywords' => ['plus', 'square', 'fill', 'add']],
            ['name' => 'Dash', 'class' => 'bi-dash', 'category' => 'ui', 'keywords' => ['dash', 'minus', 'subtract', 'remove', 'decrease']],
            ['name' => 'Dash Circle', 'class' => 'bi-dash-circle', 'category' => 'ui', 'keywords' => ['dash', 'circle', 'minus', 'subtract']],
            ['name' => 'Dash Circle Fill', 'class' => 'bi-dash-circle-fill', 'category' => 'ui', 'keywords' => ['dash', 'circle', 'fill', 'minus']],
            ['name' => 'X', 'class' => 'bi-x', 'category' => 'ui', 'keywords' => ['x', 'close', 'cancel', 'remove', 'delete']],
            ['name' => 'X Circle', 'class' => 'bi-x-circle', 'category' => 'ui', 'keywords' => ['x', 'circle', 'close', 'cancel']],
            ['name' => 'X Circle Fill', 'class' => 'bi-x-circle-fill', 'category' => 'ui', 'keywords' => ['x', 'circle', 'fill', 'close']],
            ['name' => 'Check', 'class' => 'bi-check', 'category' => 'ui', 'keywords' => ['check', 'confirm', 'ok', 'success', 'done']],
            ['name' => 'Check Circle', 'class' => 'bi-check-circle', 'category' => 'ui', 'keywords' => ['check', 'circle', 'confirm', 'success']],
            ['name' => 'Check Circle Fill', 'class' => 'bi-check-circle-fill', 'category' => 'ui', 'keywords' => ['check', 'circle', 'fill', 'success']],
            ['name' => 'Check Square', 'class' => 'bi-check-square', 'category' => 'ui', 'keywords' => ['check', 'square', 'confirm', 'checkbox']],
            ['name' => 'Check Square Fill', 'class' => 'bi-check-square-fill', 'category' => 'ui', 'keywords' => ['check', 'square', 'fill', 'checkbox']],
            ['name' => 'Three Dots', 'class' => 'bi-three-dots', 'category' => 'ui', 'keywords' => ['three', 'dots', 'more', 'menu', 'options']],
            ['name' => 'Three Dots Vertical', 'class' => 'bi-three-dots-vertical', 'category' => 'ui', 'keywords' => ['three', 'dots', 'vertical', 'menu']],
            ['name' => 'List', 'class' => 'bi-list', 'category' => 'ui', 'keywords' => ['list', 'menu', 'lines', 'items', 'hamburger']],
            ['name' => 'List Ul', 'class' => 'bi-list-ul', 'category' => 'ui', 'keywords' => ['list', 'ul', 'bullet', 'items']],
            ['name' => 'List Ol', 'class' => 'bi-list-ol', 'category' => 'ui', 'keywords' => ['list', 'ol', 'numbered', 'items']],
            ['name' => 'Grid', 'class' => 'bi-grid', 'category' => 'ui', 'keywords' => ['grid', 'layout', 'table', 'cells', 'matrix']],
            ['name' => 'Grid Fill', 'class' => 'bi-grid-fill', 'category' => 'ui', 'keywords' => ['grid', 'fill', 'layout', 'table']],
            ['name' => 'Grid 3x3', 'class' => 'bi-grid-3x3', 'category' => 'ui', 'keywords' => ['grid', '3x3', 'layout', 'nine']],
            ['name' => 'Grid 3x3 Gap', 'class' => 'bi-grid-3x3-gap', 'category' => 'ui', 'keywords' => ['grid', '3x3', 'gap', 'layout']],
            ['name' => 'Grid 3x3 Gap Fill', 'class' => 'bi-grid-3x3-gap-fill', 'category' => 'ui', 'keywords' => ['grid', '3x3', 'gap', 'fill']],
            ['name' => 'Filter', 'class' => 'bi-filter', 'category' => 'ui', 'keywords' => ['filter', 'sort', 'organize', 'search', 'refine']],
            ['name' => 'Filter Circle', 'class' => 'bi-filter-circle', 'category' => 'ui', 'keywords' => ['filter', 'circle', 'sort', 'organize']],
            ['name' => 'Filter Circle Fill', 'class' => 'bi-filter-circle-fill', 'category' => 'ui', 'keywords' => ['filter', 'circle', 'fill', 'sort']],
        ],
        
        'communications' => [
            ['name' => 'Envelope', 'class' => 'bi-envelope', 'category' => 'communications', 'keywords' => ['envelope', 'mail', 'email', 'letter', 'message']],
            ['name' => 'Envelope Fill', 'class' => 'bi-envelope-fill', 'category' => 'communications', 'keywords' => ['envelope', 'fill', 'mail', 'email']],
            ['name' => 'Envelope Open', 'class' => 'bi-envelope-open', 'category' => 'communications', 'keywords' => ['envelope', 'open', 'mail', 'read']],
            ['name' => 'Envelope Open Fill', 'class' => 'bi-envelope-open-fill', 'category' => 'communications', 'keywords' => ['envelope', 'open', 'fill', 'mail']],
            ['name' => 'At', 'class' => 'bi-at', 'category' => 'communications', 'keywords' => ['at', 'email', 'symbol', 'address', 'mention']],
            ['name' => 'Telephone', 'class' => 'bi-telephone', 'category' => 'communications', 'keywords' => ['telephone', 'phone', 'call', 'contact', 'communication']],
            ['name' => 'Telephone Fill', 'class' => 'bi-telephone-fill', 'category' => 'communications', 'keywords' => ['telephone', 'fill', 'phone', 'call']],
            ['name' => 'Telephone Inbound', 'class' => 'bi-telephone-inbound', 'category' => 'communications', 'keywords' => ['telephone', 'inbound', 'incoming', 'call']],
            ['name' => 'Telephone Inbound Fill', 'class' => 'bi-telephone-inbound-fill', 'category' => 'communications', 'keywords' => ['telephone', 'inbound', 'fill', 'incoming']],
            ['name' => 'Telephone Outbound', 'class' => 'bi-telephone-outbound', 'category' => 'communications', 'keywords' => ['telephone', 'outbound', 'outgoing', 'call']],
            ['name' => 'Telephone Outbound Fill', 'class' => 'bi-telephone-outbound-fill', 'category' => 'communications', 'keywords' => ['telephone', 'outbound', 'fill', 'outgoing']],
            ['name' => 'Telephone X', 'class' => 'bi-telephone-x', 'category' => 'communications', 'keywords' => ['telephone', 'x', 'decline', 'reject', 'hang']],
            ['name' => 'Telephone X Fill', 'class' => 'bi-telephone-x-fill', 'category' => 'communications', 'keywords' => ['telephone', 'x', 'fill', 'decline']],
            ['name' => 'Phone', 'class' => 'bi-phone', 'category' => 'communications', 'keywords' => ['phone', 'mobile', 'cell', 'smartphone', 'device']],
            ['name' => 'Phone Fill', 'class' => 'bi-phone-fill', 'category' => 'communications', 'keywords' => ['phone', 'fill', 'mobile', 'smartphone']],
            ['name' => 'Phone Landscape', 'class' => 'bi-phone-landscape', 'category' => 'communications', 'keywords' => ['phone', 'landscape', 'horizontal', 'mobile']],
            ['name' => 'Phone Landscape Fill', 'class' => 'bi-phone-landscape-fill', 'category' => 'communications', 'keywords' => ['phone', 'landscape', 'fill', 'horizontal']],
            ['name' => 'Chat', 'class' => 'bi-chat', 'category' => 'communications', 'keywords' => ['chat', 'message', 'conversation', 'talk', 'bubble']],
            ['name' => 'Chat Fill', 'class' => 'bi-chat-fill', 'category' => 'communications', 'keywords' => ['chat', 'fill', 'message', 'conversation']],
            ['name' => 'Chat Dots', 'class' => 'bi-chat-dots', 'category' => 'communications', 'keywords' => ['chat', 'dots', 'typing', 'message']],
            ['name' => 'Chat Dots Fill', 'class' => 'bi-chat-dots-fill', 'category' => 'communications', 'keywords' => ['chat', 'dots', 'fill', 'typing']],
            ['name' => 'Chat Left', 'class' => 'bi-chat-left', 'category' => 'communications', 'keywords' => ['chat', 'left', 'message', 'bubble']],
            ['name' => 'Chat Left Fill', 'class' => 'bi-chat-left-fill', 'category' => 'communications', 'keywords' => ['chat', 'left', 'fill', 'message']],
            ['name' => 'Chat Left Dots', 'class' => 'bi-chat-left-dots', 'category' => 'communications', 'keywords' => ['chat', 'left', 'dots', 'typing']],
            ['name' => 'Chat Left Dots Fill', 'class' => 'bi-chat-left-dots-fill', 'category' => 'communications', 'keywords' => ['chat', 'left', 'dots', 'fill']],
            ['name' => 'Chat Left Heart', 'class' => 'bi-chat-left-heart', 'category' => 'communications', 'keywords' => ['chat', 'left', 'heart', 'love']],
            ['name' => 'Chat Left Heart Fill', 'class' => 'bi-chat-left-heart-fill', 'category' => 'communications', 'keywords' => ['chat', 'left', 'heart', 'fill']],
            ['name' => 'Chat Left Quote', 'class' => 'bi-chat-left-quote', 'category' => 'communications', 'keywords' => ['chat', 'left', 'quote', 'message']],
            ['name' => 'Chat Left Quote Fill', 'class' => 'bi-chat-left-quote-fill', 'category' => 'communications', 'keywords' => ['chat', 'left', 'quote', 'fill']],
            ['name' => 'Chat Left Text', 'class' => 'bi-chat-left-text', 'category' => 'communications', 'keywords' => ['chat', 'left', 'text', 'message']],
            ['name' => 'Chat Left Text Fill', 'class' => 'bi-chat-left-text-fill', 'category' => 'communications', 'keywords' => ['chat', 'left', 'text', 'fill']],
        ],
        
        'files' => [
            ['name' => 'File', 'class' => 'bi-file', 'category' => 'files', 'keywords' => ['file', 'document', 'paper', 'text', 'content']],
            ['name' => 'File Fill', 'class' => 'bi-file-fill', 'category' => 'files', 'keywords' => ['file', 'fill', 'document', 'paper']],
            ['name' => 'File Text', 'class' => 'bi-file-text', 'category' => 'files', 'keywords' => ['file', 'text', 'document', 'content', 'write']],
            ['name' => 'File Text Fill', 'class' => 'bi-file-text-fill', 'category' => 'files', 'keywords' => ['file', 'text', 'fill', 'document']],
            ['name' => 'File Earmark', 'class' => 'bi-file-earmark', 'category' => 'files', 'keywords' => ['file', 'earmark', 'document', 'corner', 'folded']],
            ['name' => 'File Earmark Fill', 'class' => 'bi-file-earmark-fill', 'category' => 'files', 'keywords' => ['file', 'earmark', 'fill', 'document']],
            ['name' => 'File Earmark Text', 'class' => 'bi-file-earmark-text', 'category' => 'files', 'keywords' => ['file', 'earmark', 'text', 'document']],
            ['name' => 'File Earmark Text Fill', 'class' => 'bi-file-earmark-text-fill', 'category' => 'files', 'keywords' => ['file', 'earmark', 'text', 'fill']],
            ['name' => 'Folder', 'class' => 'bi-folder', 'category' => 'files', 'keywords' => ['folder', 'directory', 'organize', 'files', 'storage']],
            ['name' => 'Folder Fill', 'class' => 'bi-folder-fill', 'category' => 'files', 'keywords' => ['folder', 'fill', 'directory', 'organize']],
            ['name' => 'Folder2', 'class' => 'bi-folder2', 'category' => 'files', 'keywords' => ['folder2', 'directory', 'organize', 'files']],
            ['name' => 'Folder2 Open', 'class' => 'bi-folder2-open', 'category' => 'files', 'keywords' => ['folder2', 'open', 'directory', 'access']],
            ['name' => 'Folder Open', 'class' => 'bi-folder-open', 'category' => 'files', 'keywords' => ['folder', 'open', 'directory', 'access', 'view']],
            ['name' => 'Folder Plus', 'class' => 'bi-folder-plus', 'category' => 'files', 'keywords' => ['folder', 'plus', 'add', 'new', 'create']],
            ['name' => 'Folder Minus', 'class' => 'bi-folder-minus', 'category' => 'files', 'keywords' => ['folder', 'minus', 'remove', 'delete', 'subtract']],
            ['name' => 'Folder Check', 'class' => 'bi-folder-check', 'category' => 'files', 'keywords' => ['folder', 'check', 'confirm', 'verified', 'done']],
            ['name' => 'Folder X', 'class' => 'bi-folder-x', 'category' => 'files', 'keywords' => ['folder', 'x', 'delete', 'remove', 'error']],
            ['name' => 'Archive', 'class' => 'bi-archive', 'category' => 'files', 'keywords' => ['archive', 'zip', 'compress', 'storage', 'backup']],
            ['name' => 'Archive Fill', 'class' => 'bi-archive-fill', 'category' => 'files', 'keywords' => ['archive', 'fill', 'zip', 'compress']],
            ['name' => 'Download', 'class' => 'bi-download', 'category' => 'files', 'keywords' => ['download', 'save', 'get', 'receive', 'arrow']],
            ['name' => 'Upload', 'class' => 'bi-upload', 'category' => 'files', 'keywords' => ['upload', 'send', 'transfer', 'share', 'arrow']],
            ['name' => 'Cloud', 'class' => 'bi-cloud', 'category' => 'files', 'keywords' => ['cloud', 'storage', 'online', 'sync', 'backup']],
            ['name' => 'Cloud Fill', 'class' => 'bi-cloud-fill', 'category' => 'files', 'keywords' => ['cloud', 'fill', 'storage', 'online']],
            ['name' => 'Cloud Arrow Down', 'class' => 'bi-cloud-arrow-down', 'category' => 'files', 'keywords' => ['cloud', 'arrow', 'down', 'download']],
            ['name' => 'Cloud Arrow Down Fill', 'class' => 'bi-cloud-arrow-down-fill', 'category' => 'files', 'keywords' => ['cloud', 'arrow', 'down', 'fill']],
            ['name' => 'Cloud Arrow Up', 'class' => 'bi-cloud-arrow-up', 'category' => 'files', 'keywords' => ['cloud', 'arrow', 'up', 'upload']],
            ['name' => 'Cloud Arrow Up Fill', 'class' => 'bi-cloud-arrow-up-fill', 'category' => 'files', 'keywords' => ['cloud', 'arrow', 'up', 'fill']],
            ['name' => 'Cloud Check', 'class' => 'bi-cloud-check', 'category' => 'files', 'keywords' => ['cloud', 'check', 'sync', 'verified', 'done']],
            ['name' => 'Cloud Check Fill', 'class' => 'bi-cloud-check-fill', 'category' => 'files', 'keywords' => ['cloud', 'check', 'fill', 'sync']],
            ['name' => 'Cloud Download', 'class' => 'bi-cloud-download', 'category' => 'files', 'keywords' => ['cloud', 'download', 'sync', 'get', 'receive']],
            ['name' => 'Cloud Download Fill', 'class' => 'bi-cloud-download-fill', 'category' => 'files', 'keywords' => ['cloud', 'download', 'fill', 'sync']],
            ['name' => 'Cloud Upload', 'class' => 'bi-cloud-upload', 'category' => 'files', 'keywords' => ['cloud', 'upload', 'sync', 'send', 'share']],
            ['name' => 'Cloud Upload Fill', 'class' => 'bi-cloud-upload-fill', 'category' => 'files', 'keywords' => ['cloud', 'upload', 'fill', 'sync']],
        ],
        
        'media' => [
            ['name' => 'Play', 'class' => 'bi-play', 'category' => 'media', 'keywords' => ['play', 'start', 'begin', 'video', 'audio']],
            ['name' => 'Play Fill', 'class' => 'bi-play-fill', 'category' => 'media', 'keywords' => ['play', 'fill', 'start', 'video']],
            ['name' => 'Play Circle', 'class' => 'bi-play-circle', 'category' => 'media', 'keywords' => ['play', 'circle', 'start', 'video']],
            ['name' => 'Play Circle Fill', 'class' => 'bi-play-circle-fill', 'category' => 'media', 'keywords' => ['play', 'circle', 'fill', 'start']],
            ['name' => 'Pause', 'class' => 'bi-pause', 'category' => 'media', 'keywords' => ['pause', 'stop', 'break', 'halt', 'suspend']],
            ['name' => 'Pause Fill', 'class' => 'bi-pause-fill', 'category' => 'media', 'keywords' => ['pause', 'fill', 'stop', 'break']],
            ['name' => 'Pause Circle', 'class' => 'bi-pause-circle', 'category' => 'media', 'keywords' => ['pause', 'circle', 'stop', 'break']],
            ['name' => 'Pause Circle Fill', 'class' => 'bi-pause-circle-fill', 'category' => 'media', 'keywords' => ['pause', 'circle', 'fill', 'stop']],
            ['name' => 'Stop', 'class' => 'bi-stop', 'category' => 'media', 'keywords' => ['stop', 'end', 'halt', 'terminate', 'finish']],
            ['name' => 'Stop Fill', 'class' => 'bi-stop-fill', 'category' => 'media', 'keywords' => ['stop', 'fill', 'end', 'halt']],
            ['name' => 'Stop Circle', 'class' => 'bi-stop-circle', 'category' => 'media', 'keywords' => ['stop', 'circle', 'end', 'halt']],
            ['name' => 'Stop Circle Fill', 'class' => 'bi-stop-circle-fill', 'category' => 'media', 'keywords' => ['stop', 'circle', 'fill', 'end']],
            ['name' => 'Skip Start', 'class' => 'bi-skip-start', 'category' => 'media', 'keywords' => ['skip', 'start', 'beginning', 'first', 'rewind']],
            ['name' => 'Skip Start Fill', 'class' => 'bi-skip-start-fill', 'category' => 'media', 'keywords' => ['skip', 'start', 'fill', 'beginning']],
            ['name' => 'Skip End', 'class' => 'bi-skip-end', 'category' => 'media', 'keywords' => ['skip', 'end', 'finish', 'last', 'forward']],
            ['name' => 'Skip End Fill', 'class' => 'bi-skip-end-fill', 'category' => 'media', 'keywords' => ['skip', 'end', 'fill', 'finish']],
            ['name' => 'Skip Forward', 'class' => 'bi-skip-forward', 'category' => 'media', 'keywords' => ['skip', 'forward', 'next', 'advance', 'fast']],
            ['name' => 'Skip Forward Fill', 'class' => 'bi-skip-forward-fill', 'category' => 'media', 'keywords' => ['skip', 'forward', 'fill', 'next']],
            ['name' => 'Skip Backward', 'class' => 'bi-skip-backward', 'category' => 'media', 'keywords' => ['skip', 'backward', 'previous', 'rewind', 'back']],
            ['name' => 'Skip Backward Fill', 'class' => 'bi-skip-backward-fill', 'category' => 'media', 'keywords' => ['skip', 'backward', 'fill', 'previous']],
            ['name' => 'Volume Off', 'class' => 'bi-volume-off', 'category' => 'media', 'keywords' => ['volume', 'off', 'mute', 'silent', 'sound']],
            ['name' => 'Volume Off Fill', 'class' => 'bi-volume-off-fill', 'category' => 'media', 'keywords' => ['volume', 'off', 'fill', 'mute']],
            ['name' => 'Volume Down', 'class' => 'bi-volume-down', 'category' => 'media', 'keywords' => ['volume', 'down', 'quiet', 'low', 'sound']],
            ['name' => 'Volume Down Fill', 'class' => 'bi-volume-down-fill', 'category' => 'media', 'keywords' => ['volume', 'down', 'fill', 'quiet']],
            ['name' => 'Volume Up', 'class' => 'bi-volume-up', 'category' => 'media', 'keywords' => ['volume', 'up', 'loud', 'high', 'sound']],
            ['name' => 'Volume Up Fill', 'class' => 'bi-volume-up-fill', 'category' => 'media', 'keywords' => ['volume', 'up', 'fill', 'loud']],
            ['name' => 'Camera', 'class' => 'bi-camera', 'category' => 'media', 'keywords' => ['camera', 'photo', 'picture', 'image', 'capture']],
            ['name' => 'Camera Fill', 'class' => 'bi-camera-fill', 'category' => 'media', 'keywords' => ['camera', 'fill', 'photo', 'picture']],
            ['name' => 'Camera Video', 'class' => 'bi-camera-video', 'category' => 'media', 'keywords' => ['camera', 'video', 'record', 'film', 'capture']],
            ['name' => 'Camera Video Fill', 'class' => 'bi-camera-video-fill', 'category' => 'media', 'keywords' => ['camera', 'video', 'fill', 'record']],
            ['name' => 'Mic', 'class' => 'bi-mic', 'category' => 'media', 'keywords' => ['mic', 'microphone', 'audio', 'record', 'sound']],
            ['name' => 'Mic Fill', 'class' => 'bi-mic-fill', 'category' => 'media', 'keywords' => ['mic', 'fill', 'microphone', 'audio']],
            ['name' => 'Mic Mute', 'class' => 'bi-mic-mute', 'category' => 'media', 'keywords' => ['mic', 'mute', 'microphone', 'silent', 'off']],
            ['name' => 'Mic Mute Fill', 'class' => 'bi-mic-mute-fill', 'category' => 'media', 'keywords' => ['mic', 'mute', 'fill', 'microphone']],
        ],
        
        'people' => [
            ['name' => 'Person', 'class' => 'bi-person', 'category' => 'people', 'keywords' => ['person', 'user', 'profile', 'account', 'human']],
            ['name' => 'Person Fill', 'class' => 'bi-person-fill', 'category' => 'people', 'keywords' => ['person', 'fill', 'user', 'profile']],
            ['name' => 'Person Circle', 'class' => 'bi-person-circle', 'category' => 'people', 'keywords' => ['person', 'circle', 'user', 'avatar', 'profile']],
            ['name' => 'Person Square', 'class' => 'bi-person-square', 'category' => 'people', 'keywords' => ['person', 'square', 'user', 'avatar', 'profile']],
            ['name' => 'Person Plus', 'class' => 'bi-person-plus', 'category' => 'people', 'keywords' => ['person', 'plus', 'add', 'user', 'invite']],
            ['name' => 'Person Plus Fill', 'class' => 'bi-person-plus-fill', 'category' => 'people', 'keywords' => ['person', 'plus', 'fill', 'add']],
            ['name' => 'Person Dash', 'class' => 'bi-person-dash', 'category' => 'people', 'keywords' => ['person', 'dash', 'remove', 'user', 'delete']],
            ['name' => 'Person Dash Fill', 'class' => 'bi-person-dash-fill', 'category' => 'people', 'keywords' => ['person', 'dash', 'fill', 'remove']],
            ['name' => 'Person X', 'class' => 'bi-person-x', 'category' => 'people', 'keywords' => ['person', 'x', 'block', 'remove', 'ban']],
            ['name' => 'Person X Fill', 'class' => 'bi-person-x-fill', 'category' => 'people', 'keywords' => ['person', 'x', 'fill', 'block']],
            ['name' => 'Person Check', 'class' => 'bi-person-check', 'category' => 'people', 'keywords' => ['person', 'check', 'verify', 'approve', 'confirm']],
            ['name' => 'Person Check Fill', 'class' => 'bi-person-check-fill', 'category' => 'people', 'keywords' => ['person', 'check', 'fill', 'verify']],
            ['name' => 'People', 'class' => 'bi-people', 'category' => 'people', 'keywords' => ['people', 'group', 'team', 'users', 'multiple']],
            ['name' => 'People Fill', 'class' => 'bi-people-fill', 'category' => 'people', 'keywords' => ['people', 'fill', 'group', 'team']],
            ['name' => 'Person Badge', 'class' => 'bi-person-badge', 'category' => 'people', 'keywords' => ['person', 'badge', 'id', 'card', 'identity']],
            ['name' => 'Person Badge Fill', 'class' => 'bi-person-badge-fill', 'category' => 'people', 'keywords' => ['person', 'badge', 'fill', 'id']],
            ['name' => 'Person Bounding Box', 'class' => 'bi-person-bounding-box', 'category' => 'people', 'keywords' => ['person', 'bounding', 'box', 'frame', 'detection']],
            ['name' => 'Person Hearts', 'class' => 'bi-person-hearts', 'category' => 'people', 'keywords' => ['person', 'hearts', 'love', 'relationship', 'affection']],
            ['name' => 'Person Workspace', 'class' => 'bi-person-workspace', 'category' => 'people', 'keywords' => ['person', 'workspace', 'office', 'work', 'desk']],
        ],
        
        'alphanumeric' => [
            ['name' => '0 Circle', 'class' => 'bi-0-circle', 'category' => 'alphanumeric', 'keywords' => ['0', 'zero', 'circle', 'number', 'digit']],
            ['name' => '0 Circle Fill', 'class' => 'bi-0-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['0', 'zero', 'circle', 'fill', 'number']],
            ['name' => '0 Square', 'class' => 'bi-0-square', 'category' => 'alphanumeric', 'keywords' => ['0', 'zero', 'square', 'number', 'digit']],
            ['name' => '0 Square Fill', 'class' => 'bi-0-square-fill', 'category' => 'alphanumeric', 'keywords' => ['0', 'zero', 'square', 'fill', 'number']],
            ['name' => '1 Circle', 'class' => 'bi-1-circle', 'category' => 'alphanumeric', 'keywords' => ['1', 'one', 'circle', 'number', 'first']],
            ['name' => '1 Circle Fill', 'class' => 'bi-1-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['1', 'one', 'circle', 'fill', 'number']],
            ['name' => '1 Square', 'class' => 'bi-1-square', 'category' => 'alphanumeric', 'keywords' => ['1', 'one', 'square', 'number', 'first']],
            ['name' => '1 Square Fill', 'class' => 'bi-1-square-fill', 'category' => 'alphanumeric', 'keywords' => ['1', 'one', 'square', 'fill', 'number']],
            ['name' => '2 Circle', 'class' => 'bi-2-circle', 'category' => 'alphanumeric', 'keywords' => ['2', 'two', 'circle', 'number', 'second']],
            ['name' => '2 Circle Fill', 'class' => 'bi-2-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['2', 'two', 'circle', 'fill', 'number']],
            ['name' => '2 Square', 'class' => 'bi-2-square', 'category' => 'alphanumeric', 'keywords' => ['2', 'two', 'square', 'number', 'second']],
            ['name' => '2 Square Fill', 'class' => 'bi-2-square-fill', 'category' => 'alphanumeric', 'keywords' => ['2', 'two', 'square', 'fill', 'number']],
            ['name' => '3 Circle', 'class' => 'bi-3-circle', 'category' => 'alphanumeric', 'keywords' => ['3', 'three', 'circle', 'number', 'third']],
            ['name' => '3 Circle Fill', 'class' => 'bi-3-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['3', 'three', 'circle', 'fill', 'number']],
            ['name' => '3 Square', 'class' => 'bi-3-square', 'category' => 'alphanumeric', 'keywords' => ['3', 'three', 'square', 'number', 'third']],
            ['name' => '3 Square Fill', 'class' => 'bi-3-square-fill', 'category' => 'alphanumeric', 'keywords' => ['3', 'three', 'square', 'fill', 'number']],
            ['name' => '4 Circle', 'class' => 'bi-4-circle', 'category' => 'alphanumeric', 'keywords' => ['4', 'four', 'circle', 'number', 'fourth']],
            ['name' => '4 Circle Fill', 'class' => 'bi-4-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['4', 'four', 'circle', 'fill', 'number']],
            ['name' => '4 Square', 'class' => 'bi-4-square', 'category' => 'alphanumeric', 'keywords' => ['4', 'four', 'square', 'number', 'fourth']],
            ['name' => '4 Square Fill', 'class' => 'bi-4-square-fill', 'category' => 'alphanumeric', 'keywords' => ['4', 'four', 'square', 'fill', 'number']],
            ['name' => '5 Circle', 'class' => 'bi-5-circle', 'category' => 'alphanumeric', 'keywords' => ['5', 'five', 'circle', 'number', 'fifth']],
            ['name' => '5 Circle Fill', 'class' => 'bi-5-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['5', 'five', 'circle', 'fill', 'number']],
            ['name' => '5 Square', 'class' => 'bi-5-square', 'category' => 'alphanumeric', 'keywords' => ['5', 'five', 'square', 'number', 'fifth']],
            ['name' => '5 Square Fill', 'class' => 'bi-5-square-fill', 'category' => 'alphanumeric', 'keywords' => ['5', 'five', 'square', 'fill', 'number']],
            ['name' => '6 Circle', 'class' => 'bi-6-circle', 'category' => 'alphanumeric', 'keywords' => ['6', 'six', 'circle', 'number', 'sixth']],
            ['name' => '6 Circle Fill', 'class' => 'bi-6-circle-fill', 'category' => 'alphanumeric', 'keywords' => ['6', 'six', 'circle', 'fill', 'number']],
            ['name' => '6 Square', 'class' => 'bi-6-square', 'category' => 'alphanumeric', 'keywords' => ['6', 'six', 'square', 'number', 'sixth']],
            ['name' => '6 Square Fill', 'class' => 'bi-6-square-fill', 'category' => 'alphanumeric', 'keywords' => ['6', 'six', 'square', 'fill', 'number']],
        ],
        
        'others' => [
            ['name' => 'Sun', 'class' => 'bi-sun', 'category' => 'others', 'keywords' => ['sun', 'light', 'day', 'bright', 'weather']],
            ['name' => 'Sun Fill', 'class' => 'bi-sun-fill', 'category' => 'others', 'keywords' => ['sun', 'fill', 'light', 'day']],
            ['name' => 'Moon', 'class' => 'bi-moon', 'category' => 'others', 'keywords' => ['moon', 'night', 'dark', 'theme', 'weather']],
            ['name' => 'Moon Fill', 'class' => 'bi-moon-fill', 'category' => 'others', 'keywords' => ['moon', 'fill', 'night', 'dark']],
            ['name' => 'Moon Stars', 'class' => 'bi-moon-stars', 'category' => 'others', 'keywords' => ['moon', 'stars', 'night', 'sky', 'weather']],
            ['name' => 'Moon Stars Fill', 'class' => 'bi-moon-stars-fill', 'category' => 'others', 'keywords' => ['moon', 'stars', 'fill', 'night']],
            ['name' => 'Cloud Rain', 'class' => 'bi-cloud-rain', 'category' => 'others', 'keywords' => ['cloud', 'rain', 'weather', 'storm', 'water']],
            ['name' => 'Cloud Rain Fill', 'class' => 'bi-cloud-rain-fill', 'category' => 'others', 'keywords' => ['cloud', 'rain', 'fill', 'weather']],
            ['name' => 'Cloud Snow', 'class' => 'bi-cloud-snow', 'category' => 'others', 'keywords' => ['cloud', 'snow', 'weather', 'winter', 'cold']],
            ['name' => 'Cloud Snow Fill', 'class' => 'bi-cloud-snow-fill', 'category' => 'others', 'keywords' => ['cloud', 'snow', 'fill', 'weather']],
            ['name' => 'Lightning', 'class' => 'bi-lightning', 'category' => 'others', 'keywords' => ['lightning', 'bolt', 'storm', 'weather', 'electric']],
            ['name' => 'Lightning Fill', 'class' => 'bi-lightning-fill', 'category' => 'others', 'keywords' => ['lightning', 'fill', 'bolt', 'storm']],
            ['name' => 'Lightning Charge', 'class' => 'bi-lightning-charge', 'category' => 'others', 'keywords' => ['lightning', 'charge', 'electric', 'power', 'energy']],
            ['name' => 'Lightning Charge Fill', 'class' => 'bi-lightning-charge-fill', 'category' => 'others', 'keywords' => ['lightning', 'charge', 'fill', 'electric']],
            ['name' => 'Geo', 'class' => 'bi-geo', 'category' => 'others', 'keywords' => ['geo', 'location', 'pin', 'map', 'place']],
            ['name' => 'Geo Fill', 'class' => 'bi-geo-fill', 'category' => 'others', 'keywords' => ['geo', 'fill', 'location', 'pin']],
            ['name' => 'Geo Alt', 'class' => 'bi-geo-alt', 'category' => 'others', 'keywords' => ['geo', 'alt', 'location', 'pin', 'map']],
            ['name' => 'Geo Alt Fill', 'class' => 'bi-geo-alt-fill', 'category' => 'others', 'keywords' => ['geo', 'alt', 'fill', 'location']],
            ['name' => 'Globe', 'class' => 'bi-globe', 'category' => 'others', 'keywords' => ['globe', 'world', 'earth', 'international', 'global']],
            ['name' => 'Globe2', 'class' => 'bi-globe2', 'category' => 'others', 'keywords' => ['globe2', 'world', 'earth', 'international']],
            ['name' => 'Map', 'class' => 'bi-map', 'category' => 'others', 'keywords' => ['map', 'location', 'navigation', 'geography', 'route']],
            ['name' => 'Map Fill', 'class' => 'bi-map-fill', 'category' => 'others', 'keywords' => ['map', 'fill', 'location', 'navigation']],
            ['name' => 'Compass', 'class' => 'bi-compass', 'category' => 'others', 'keywords' => ['compass', 'direction', 'navigation', 'north', 'orientation']],
            ['name' => 'Compass Fill', 'class' => 'bi-compass-fill', 'category' => 'others', 'keywords' => ['compass', 'fill', 'direction', 'navigation']],
            ['name' => 'Cash', 'class' => 'bi-cash', 'category' => 'others', 'keywords' => ['cash', 'money', 'currency', 'payment', 'dollar']],
            ['name' => 'Cash Stack', 'class' => 'bi-cash-stack', 'category' => 'others', 'keywords' => ['cash', 'stack', 'money', 'bills', 'currency']],
            ['name' => 'Credit Card', 'class' => 'bi-credit-card', 'category' => 'others', 'keywords' => ['credit', 'card', 'payment', 'money', 'finance']],
            ['name' => 'Credit Card Fill', 'class' => 'bi-credit-card-fill', 'category' => 'others', 'keywords' => ['credit', 'card', 'fill', 'payment']],
            ['name' => 'Wallet', 'class' => 'bi-wallet', 'category' => 'others', 'keywords' => ['wallet', 'money', 'purse', 'finance', 'payment']],
            ['name' => 'Wallet Fill', 'class' => 'bi-wallet-fill', 'category' => 'others', 'keywords' => ['wallet', 'fill', 'money', 'purse']],
            ['name' => 'Wallet2', 'class' => 'bi-wallet2', 'category' => 'others', 'keywords' => ['wallet2', 'money', 'purse', 'finance']],
            ['name' => 'Piggy Bank', 'class' => 'bi-piggy-bank', 'category' => 'others', 'keywords' => ['piggy', 'bank', 'savings', 'money', 'save']],
            ['name' => 'Piggy Bank Fill', 'class' => 'bi-piggy-bank-fill', 'category' => 'others', 'keywords' => ['piggy', 'bank', 'fill', 'savings']],
        ],
    ],
    
    /**
     * 載入優先級定義
     * 
     * 從前端 loadingPriority 轉換，用於 API 分類載入順序
     */
    'loading_priority' => [
        'immediate' => ['general'],
        'high' => ['ui', 'communications'],
        'medium' => ['files', 'media', 'people'],
        'low' => ['alphanumeric', 'others']
    ],
];