<?php

/**
 * Hero Icons 配置
 * 
 * 從前端 allHeroicons.js 完整提取的 Hero Icons v1 清單
 * 包含 230 個 outline 樣式的圖標，包含分類和關鍵字資料
 */

return [
    /**
     * Hero Icons v1 完整清單（outline 樣式）
     * 
     * 每個圖標包含：
     * - name: 顯示名稱
     * - component: Vue 組件名稱
     * - category: 分類
     * - keywords: 搜尋關鍵字陣列
     */
    'icons' => [
        ['name' => 'Academic Cap', 'component' => 'AcademicCapIcon', 'category' => 'general', 'keywords' => ['education', 'graduation', 'school', 'university', 'learning']],
        ['name' => 'Adjustments', 'component' => 'AdjustmentsIcon', 'category' => 'ui', 'keywords' => ['settings', 'controls', 'sliders', 'options']],
        ['name' => 'Annotation', 'component' => 'AnnotationIcon', 'category' => 'communication', 'keywords' => ['comment', 'note', 'message', 'feedback']],
        ['name' => 'Archive', 'component' => 'ArchiveIcon', 'category' => 'media', 'keywords' => ['storage', 'box', 'organize', 'save']],
        ['name' => 'Arrow Circle Down', 'component' => 'ArrowCircleDownIcon', 'category' => 'navigation', 'keywords' => ['down', 'direction', 'move', 'circle']],
        ['name' => 'Arrow Circle Left', 'component' => 'ArrowCircleLeftIcon', 'category' => 'navigation', 'keywords' => ['left', 'direction', 'move', 'circle']],
        ['name' => 'Arrow Circle Right', 'component' => 'ArrowCircleRightIcon', 'category' => 'navigation', 'keywords' => ['right', 'direction', 'move', 'circle']],
        ['name' => 'Arrow Circle Up', 'component' => 'ArrowCircleUpIcon', 'category' => 'navigation', 'keywords' => ['up', 'direction', 'move', 'circle']],
        ['name' => 'Arrow Down', 'component' => 'ArrowDownIcon', 'category' => 'navigation', 'keywords' => ['down', 'direction', 'move']],
        ['name' => 'Arrow Left', 'component' => 'ArrowLeftIcon', 'category' => 'navigation', 'keywords' => ['left', 'direction', 'move']],
        ['name' => 'Arrow Narrow Down', 'component' => 'ArrowNarrowDownIcon', 'category' => 'navigation', 'keywords' => ['down', 'direction', 'move', 'narrow']],
        ['name' => 'Arrow Narrow Left', 'component' => 'ArrowNarrowLeftIcon', 'category' => 'navigation', 'keywords' => ['left', 'direction', 'move', 'narrow']],
        ['name' => 'Arrow Narrow Right', 'component' => 'ArrowNarrowRightIcon', 'category' => 'navigation', 'keywords' => ['right', 'direction', 'move', 'narrow']],
        ['name' => 'Arrow Narrow Up', 'component' => 'ArrowNarrowUpIcon', 'category' => 'navigation', 'keywords' => ['up', 'direction', 'move', 'narrow']],
        ['name' => 'Arrow Right', 'component' => 'ArrowRightIcon', 'category' => 'navigation', 'keywords' => ['right', 'direction', 'move']],
        ['name' => 'Arrow Sm Down', 'component' => 'ArrowSmDownIcon', 'category' => 'navigation', 'keywords' => ['down', 'direction', 'move', 'small']],
        ['name' => 'Arrow Sm Left', 'component' => 'ArrowSmLeftIcon', 'category' => 'navigation', 'keywords' => ['left', 'direction', 'move', 'small']],
        ['name' => 'Arrow Sm Right', 'component' => 'ArrowSmRightIcon', 'category' => 'navigation', 'keywords' => ['right', 'direction', 'move', 'small']],
        ['name' => 'Arrow Sm Up', 'component' => 'ArrowSmUpIcon', 'category' => 'navigation', 'keywords' => ['up', 'direction', 'move', 'small']],
        ['name' => 'Arrow Up', 'component' => 'ArrowUpIcon', 'category' => 'navigation', 'keywords' => ['up', 'direction', 'move']],
        ['name' => 'Arrows Expand', 'component' => 'ArrowsExpandIcon', 'category' => 'ui', 'keywords' => ['expand', 'fullscreen', 'zoom', 'maximize']],
        ['name' => 'At Symbol', 'component' => 'AtSymbolIcon', 'category' => 'communication', 'keywords' => ['email', 'at', 'symbol', 'address']],
        ['name' => 'Backspace', 'component' => 'BackspaceIcon', 'category' => 'ui', 'keywords' => ['delete', 'remove', 'backspace', 'clear']],
        ['name' => 'Badge Check', 'component' => 'BadgeCheckIcon', 'category' => 'status', 'keywords' => ['verified', 'check', 'badge', 'confirm']],
        ['name' => 'Ban', 'component' => 'BanIcon', 'category' => 'status', 'keywords' => ['ban', 'block', 'stop', 'forbidden']],
        ['name' => 'Beaker', 'component' => 'BeakerIcon', 'category' => 'science', 'keywords' => ['science', 'experiment', 'laboratory', 'test']],
        ['name' => 'Bell', 'component' => 'BellIcon', 'category' => 'communication', 'keywords' => ['notification', 'alert', 'bell', 'sound']],
        ['name' => 'Book Open', 'component' => 'BookOpenIcon', 'category' => 'general', 'keywords' => ['book', 'read', 'open', 'learning']],
        ['name' => 'Bookmark', 'component' => 'BookmarkIcon', 'category' => 'general', 'keywords' => ['bookmark', 'save', 'favorite', 'mark']],
        ['name' => 'Bookmark Alt', 'component' => 'BookmarkAltIcon', 'category' => 'general', 'keywords' => ['bookmark', 'save', 'favorite', 'mark', 'alt']],
        ['name' => 'Briefcase', 'component' => 'BriefcaseIcon', 'category' => 'business', 'keywords' => ['work', 'business', 'briefcase', 'job']],
        ['name' => 'Cake', 'component' => 'CakeIcon', 'category' => 'general', 'keywords' => ['cake', 'birthday', 'celebration', 'dessert']],
        ['name' => 'Calculator', 'component' => 'CalculatorIcon', 'category' => 'general', 'keywords' => ['calculator', 'math', 'numbers', 'compute']],
        ['name' => 'Calendar', 'component' => 'CalendarIcon', 'category' => 'general', 'keywords' => ['calendar', 'date', 'time', 'schedule']],
        ['name' => 'Camera', 'component' => 'CameraIcon', 'category' => 'media', 'keywords' => ['camera', 'photo', 'picture', 'image']],
        ['name' => 'Cash', 'component' => 'CashIcon', 'category' => 'business', 'keywords' => ['money', 'cash', 'payment', 'currency']],
        ['name' => 'Chart Bar', 'component' => 'ChartBarIcon', 'category' => 'data', 'keywords' => ['chart', 'bar', 'graph', 'data', 'statistics']],
        ['name' => 'Chart Pie', 'component' => 'ChartPieIcon', 'category' => 'data', 'keywords' => ['chart', 'pie', 'graph', 'data', 'statistics']],
        ['name' => 'Chart Square Bar', 'component' => 'ChartSquareBarIcon', 'category' => 'data', 'keywords' => ['chart', 'square', 'bar', 'graph', 'data']],
        ['name' => 'Chat', 'component' => 'ChatIcon', 'category' => 'communication', 'keywords' => ['chat', 'message', 'talk', 'communication']],
        ['name' => 'Chat Alt', 'component' => 'ChatAltIcon', 'category' => 'communication', 'keywords' => ['chat', 'message', 'talk', 'communication', 'alt']],
        ['name' => 'Chat Alt2', 'component' => 'ChatAlt2Icon', 'category' => 'communication', 'keywords' => ['chat', 'message', 'talk', 'communication', 'alt2']],
        ['name' => 'Check', 'component' => 'CheckIcon', 'category' => 'status', 'keywords' => ['check', 'confirm', 'ok', 'success']],
        ['name' => 'Check Circle', 'component' => 'CheckCircleIcon', 'category' => 'status', 'keywords' => ['check', 'confirm', 'ok', 'success', 'circle']],
        ['name' => 'Chevron Double Down', 'component' => 'ChevronDoubleDownIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'down', 'double', 'direction']],
        ['name' => 'Chevron Double Left', 'component' => 'ChevronDoubleLeftIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'left', 'double', 'direction']],
        ['name' => 'Chevron Double Right', 'component' => 'ChevronDoubleRightIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'right', 'double', 'direction']],
        ['name' => 'Chevron Double Up', 'component' => 'ChevronDoubleUpIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'up', 'double', 'direction']],
        ['name' => 'Chevron Down', 'component' => 'ChevronDownIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'down', 'direction']],
        ['name' => 'Chevron Left', 'component' => 'ChevronLeftIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'left', 'direction']],
        ['name' => 'Chevron Right', 'component' => 'ChevronRightIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'right', 'direction']],
        ['name' => 'Chevron Up', 'component' => 'ChevronUpIcon', 'category' => 'navigation', 'keywords' => ['chevron', 'up', 'direction']],
        ['name' => 'Chip', 'component' => 'ChipIcon', 'category' => 'technology', 'keywords' => ['chip', 'processor', 'technology', 'hardware']],
        ['name' => 'Clipboard', 'component' => 'ClipboardIcon', 'category' => 'general', 'keywords' => ['clipboard', 'copy', 'paste', 'document']],
        ['name' => 'Clipboard Check', 'component' => 'ClipboardCheckIcon', 'category' => 'general', 'keywords' => ['clipboard', 'check', 'confirm', 'document']],
        ['name' => 'Clipboard Copy', 'component' => 'ClipboardCopyIcon', 'category' => 'general', 'keywords' => ['clipboard', 'copy', 'duplicate', 'document']],
        ['name' => 'Clipboard List', 'component' => 'ClipboardListIcon', 'category' => 'general', 'keywords' => ['clipboard', 'list', 'tasks', 'document']],
        ['name' => 'Clock', 'component' => 'ClockIcon', 'category' => 'general', 'keywords' => ['clock', 'time', 'schedule', 'timer']],
        ['name' => 'Cloud', 'component' => 'CloudIcon', 'category' => 'technology', 'keywords' => ['cloud', 'storage', 'online', 'sync']],
        ['name' => 'Cloud Download', 'component' => 'CloudDownloadIcon', 'category' => 'technology', 'keywords' => ['cloud', 'download', 'sync', 'receive']],
        ['name' => 'Cloud Upload', 'component' => 'CloudUploadIcon', 'category' => 'technology', 'keywords' => ['cloud', 'upload', 'sync', 'send']],
        ['name' => 'Code', 'component' => 'CodeIcon', 'category' => 'technology', 'keywords' => ['code', 'programming', 'development', 'script']],
        ['name' => 'Cog', 'component' => 'CogIcon', 'category' => 'ui', 'keywords' => ['settings', 'cog', 'gear', 'configuration']],
        ['name' => 'Collection', 'component' => 'CollectionIcon', 'category' => 'media', 'keywords' => ['collection', 'gallery', 'group', 'organize']],
        ['name' => 'Color Swatch', 'component' => 'ColorSwatchIcon', 'category' => 'design', 'keywords' => ['color', 'swatch', 'palette', 'design']],
        ['name' => 'Credit Card', 'component' => 'CreditCardIcon', 'category' => 'business', 'keywords' => ['credit', 'card', 'payment', 'money']],
        ['name' => 'Cube', 'component' => 'CubeIcon', 'category' => 'design', 'keywords' => ['cube', '3d', 'box', 'shape']],
        ['name' => 'Cube Transparent', 'component' => 'CubeTransparentIcon', 'category' => 'design', 'keywords' => ['cube', '3d', 'transparent', 'shape']],
        ['name' => 'Currency Bangladeshi', 'component' => 'CurrencyBangladeshiIcon', 'category' => 'business', 'keywords' => ['currency', 'bangladeshi', 'money', 'taka']],
        ['name' => 'Currency Dollar', 'component' => 'CurrencyDollarIcon', 'category' => 'business', 'keywords' => ['currency', 'dollar', 'money', 'usd']],
        ['name' => 'Currency Euro', 'component' => 'CurrencyEuroIcon', 'category' => 'business', 'keywords' => ['currency', 'euro', 'money', 'eur']],
        ['name' => 'Currency Pound', 'component' => 'CurrencyPoundIcon', 'category' => 'business', 'keywords' => ['currency', 'pound', 'money', 'gbp']],
        ['name' => 'Currency Rupee', 'component' => 'CurrencyRupeeIcon', 'category' => 'business', 'keywords' => ['currency', 'rupee', 'money', 'inr']],
        ['name' => 'Currency Yen', 'component' => 'CurrencyYenIcon', 'category' => 'business', 'keywords' => ['currency', 'yen', 'money', 'jpy']],
        ['name' => 'Cursor Click', 'component' => 'CursorClickIcon', 'category' => 'ui', 'keywords' => ['cursor', 'click', 'pointer', 'select']],
        ['name' => 'Database', 'component' => 'DatabaseIcon', 'category' => 'technology', 'keywords' => ['database', 'storage', 'data', 'server']],
        ['name' => 'Desktop Computer', 'component' => 'DesktopComputerIcon', 'category' => 'technology', 'keywords' => ['desktop', 'computer', 'pc', 'monitor']],
        ['name' => 'Device Mobile', 'component' => 'DeviceMobileIcon', 'category' => 'technology', 'keywords' => ['mobile', 'phone', 'device', 'smartphone']],
        ['name' => 'Device Tablet', 'component' => 'DeviceTabletIcon', 'category' => 'technology', 'keywords' => ['tablet', 'device', 'ipad', 'screen']],
        ['name' => 'Document', 'component' => 'DocumentIcon', 'category' => 'general', 'keywords' => ['document', 'file', 'paper', 'text']],
        ['name' => 'Document Add', 'component' => 'DocumentAddIcon', 'category' => 'general', 'keywords' => ['document', 'add', 'new', 'create']],
        ['name' => 'Document Download', 'component' => 'DocumentDownloadIcon', 'category' => 'general', 'keywords' => ['document', 'download', 'save', 'get']],
        ['name' => 'Document Duplicate', 'component' => 'DocumentDuplicateIcon', 'category' => 'general', 'keywords' => ['document', 'duplicate', 'copy', 'clone']],
        ['name' => 'Document Remove', 'component' => 'DocumentRemoveIcon', 'category' => 'general', 'keywords' => ['document', 'remove', 'delete', 'trash']],
        ['name' => 'Document Report', 'component' => 'DocumentReportIcon', 'category' => 'business', 'keywords' => ['document', 'report', 'analytics', 'data']],
        ['name' => 'Document Search', 'component' => 'DocumentSearchIcon', 'category' => 'general', 'keywords' => ['document', 'search', 'find', 'look']],
        ['name' => 'Document Text', 'component' => 'DocumentTextIcon', 'category' => 'general', 'keywords' => ['document', 'text', 'write', 'content']],
        ['name' => 'Dots Circle Horizontal', 'component' => 'DotsCircleHorizontalIcon', 'category' => 'ui', 'keywords' => ['dots', 'menu', 'more', 'options']],
        ['name' => 'Dots Horizontal', 'component' => 'DotsHorizontalIcon', 'category' => 'ui', 'keywords' => ['dots', 'menu', 'more', 'horizontal']],
        ['name' => 'Dots Vertical', 'component' => 'DotsVerticalIcon', 'category' => 'ui', 'keywords' => ['dots', 'menu', 'more', 'vertical']],
        ['name' => 'Download', 'component' => 'DownloadIcon', 'category' => 'general', 'keywords' => ['download', 'save', 'get', 'receive']],
        ['name' => 'Duplicate', 'component' => 'DuplicateIcon', 'category' => 'general', 'keywords' => ['duplicate', 'copy', 'clone', 'replicate']],
        ['name' => 'Emoji Happy', 'component' => 'EmojiHappyIcon', 'category' => 'general', 'keywords' => ['emoji', 'happy', 'smile', 'face']],
        ['name' => 'Emoji Sad', 'component' => 'EmojiSadIcon', 'category' => 'general', 'keywords' => ['emoji', 'sad', 'unhappy', 'face']],
        ['name' => 'Exclamation', 'component' => 'ExclamationIcon', 'category' => 'status', 'keywords' => ['exclamation', 'warning', 'alert', 'important']],
        ['name' => 'Exclamation Circle', 'component' => 'ExclamationCircleIcon', 'category' => 'status', 'keywords' => ['exclamation', 'warning', 'alert', 'circle']],
        ['name' => 'External Link', 'component' => 'ExternalLinkIcon', 'category' => 'navigation', 'keywords' => ['external', 'link', 'open', 'new']],
        ['name' => 'Eye', 'component' => 'EyeIcon', 'category' => 'ui', 'keywords' => ['eye', 'see', 'view', 'visible']],
        ['name' => 'Eye Off', 'component' => 'EyeOffIcon', 'category' => 'ui', 'keywords' => ['eye', 'off', 'hidden', 'invisible']],
        ['name' => 'Fast Forward', 'component' => 'FastForwardIcon', 'category' => 'media', 'keywords' => ['fast', 'forward', 'skip', 'next']],
        ['name' => 'Film', 'component' => 'FilmIcon', 'category' => 'media', 'keywords' => ['film', 'movie', 'video', 'cinema']],
        ['name' => 'Filter', 'component' => 'FilterIcon', 'category' => 'ui', 'keywords' => ['filter', 'sort', 'organize', 'search']],
        ['name' => 'Finger Print', 'component' => 'FingerPrintIcon', 'category' => 'security', 'keywords' => ['fingerprint', 'security', 'identity', 'biometric']],
        ['name' => 'Fire', 'component' => 'FireIcon', 'category' => 'general', 'keywords' => ['fire', 'hot', 'flame', 'burn']],
        ['name' => 'Flag', 'component' => 'FlagIcon', 'category' => 'general', 'keywords' => ['flag', 'mark', 'country', 'banner']],
        ['name' => 'Folder', 'component' => 'FolderIcon', 'category' => 'general', 'keywords' => ['folder', 'directory', 'organize', 'files']],
        ['name' => 'Folder Add', 'component' => 'FolderAddIcon', 'category' => 'general', 'keywords' => ['folder', 'add', 'new', 'create']],
        ['name' => 'Folder Download', 'component' => 'FolderDownloadIcon', 'category' => 'general', 'keywords' => ['folder', 'download', 'save', 'get']],
        ['name' => 'Folder Open', 'component' => 'FolderOpenIcon', 'category' => 'general', 'keywords' => ['folder', 'open', 'access', 'view']],
        ['name' => 'Folder Remove', 'component' => 'FolderRemoveIcon', 'category' => 'general', 'keywords' => ['folder', 'remove', 'delete', 'trash']],
        ['name' => 'Gift', 'component' => 'GiftIcon', 'category' => 'general', 'keywords' => ['gift', 'present', 'surprise', 'box']],
        ['name' => 'Globe', 'component' => 'GlobeIcon', 'category' => 'general', 'keywords' => ['globe', 'world', 'earth', 'international']],
        ['name' => 'Globe Alt', 'component' => 'GlobeAltIcon', 'category' => 'general', 'keywords' => ['globe', 'world', 'earth', 'international', 'alt']],
        ['name' => 'Hand', 'component' => 'HandIcon', 'category' => 'general', 'keywords' => ['hand', 'stop', 'halt', 'gesture']],
        ['name' => 'Hashtag', 'component' => 'HashtagIcon', 'category' => 'communication', 'keywords' => ['hashtag', 'tag', 'social', 'symbol']],
        ['name' => 'Heart', 'component' => 'HeartIcon', 'category' => 'general', 'keywords' => ['heart', 'love', 'like', 'favorite']],
        ['name' => 'Home', 'component' => 'HomeIcon', 'category' => 'navigation', 'keywords' => ['home', 'house', 'main', 'dashboard']],
        ['name' => 'Identification', 'component' => 'IdentificationIcon', 'category' => 'general', 'keywords' => ['identification', 'id', 'card', 'identity']],
        ['name' => 'Inbox', 'component' => 'InboxIcon', 'category' => 'communication', 'keywords' => ['inbox', 'mail', 'messages', 'receive']],
        ['name' => 'Inbox In', 'component' => 'InboxInIcon', 'category' => 'communication', 'keywords' => ['inbox', 'in', 'receive', 'mail']],
        ['name' => 'Information Circle', 'component' => 'InformationCircleIcon', 'category' => 'status', 'keywords' => ['information', 'info', 'help', 'circle']],
        ['name' => 'Key', 'component' => 'KeyIcon', 'category' => 'security', 'keywords' => ['key', 'password', 'security', 'access']],
        ['name' => 'Library', 'component' => 'LibraryIcon', 'category' => 'general', 'keywords' => ['library', 'books', 'collection', 'archive']],
        ['name' => 'Light Bulb', 'component' => 'LightBulbIcon', 'category' => 'general', 'keywords' => ['idea', 'bulb', 'light', 'creative']],
        ['name' => 'Lightning Bolt', 'component' => 'LightningBoltIcon', 'category' => 'general', 'keywords' => ['lightning', 'bolt', 'fast', 'power']],
        ['name' => 'Link', 'component' => 'LinkIcon', 'category' => 'navigation', 'keywords' => ['link', 'chain', 'connect', 'url']],
        ['name' => 'Location Marker', 'component' => 'LocationMarkerIcon', 'category' => 'navigation', 'keywords' => ['location', 'marker', 'map', 'pin']],
        ['name' => 'Lock Closed', 'component' => 'LockClosedIcon', 'category' => 'security', 'keywords' => ['lock', 'closed', 'secure', 'private']],
        ['name' => 'Lock Open', 'component' => 'LockOpenIcon', 'category' => 'security', 'keywords' => ['lock', 'open', 'unlock', 'accessible']],
        ['name' => 'Login', 'component' => 'LoginIcon', 'category' => 'security', 'keywords' => ['login', 'signin', 'enter', 'access']],
        ['name' => 'Logout', 'component' => 'LogoutIcon', 'category' => 'security', 'keywords' => ['logout', 'signout', 'exit', 'leave']],
        ['name' => 'Mail', 'component' => 'MailIcon', 'category' => 'communication', 'keywords' => ['mail', 'email', 'message', 'letter']],
        ['name' => 'Mail Open', 'component' => 'MailOpenIcon', 'category' => 'communication', 'keywords' => ['mail', 'open', 'read', 'email']],
        ['name' => 'Map', 'component' => 'MapIcon', 'category' => 'navigation', 'keywords' => ['map', 'location', 'navigation', 'geography']],
        ['name' => 'Menu', 'component' => 'MenuIcon', 'category' => 'ui', 'keywords' => ['menu', 'hamburger', 'navigation', 'list']],
        ['name' => 'Menu Alt1', 'component' => 'MenuAlt1Icon', 'category' => 'ui', 'keywords' => ['menu', 'alt1', 'navigation', 'list']],
        ['name' => 'Menu Alt2', 'component' => 'MenuAlt2Icon', 'category' => 'ui', 'keywords' => ['menu', 'alt2', 'navigation', 'list']],
        ['name' => 'Menu Alt3', 'component' => 'MenuAlt3Icon', 'category' => 'ui', 'keywords' => ['menu', 'alt3', 'navigation', 'list']],
        ['name' => 'Menu Alt4', 'component' => 'MenuAlt4Icon', 'category' => 'ui', 'keywords' => ['menu', 'alt4', 'navigation', 'list']],
        ['name' => 'Microphone', 'component' => 'MicrophoneIcon', 'category' => 'media', 'keywords' => ['microphone', 'mic', 'audio', 'record']],
        ['name' => 'Minus', 'component' => 'MinusIcon', 'category' => 'ui', 'keywords' => ['minus', 'subtract', 'remove', 'decrease']],
        ['name' => 'Minus Circle', 'component' => 'MinusCircleIcon', 'category' => 'ui', 'keywords' => ['minus', 'circle', 'subtract', 'remove']],
        ['name' => 'Minus Sm', 'component' => 'MinusSmIcon', 'category' => 'ui', 'keywords' => ['minus', 'small', 'subtract', 'remove']],
        ['name' => 'Moon', 'component' => 'MoonIcon', 'category' => 'general', 'keywords' => ['moon', 'night', 'dark', 'theme']],
        ['name' => 'Music Note', 'component' => 'MusicNoteIcon', 'category' => 'media', 'keywords' => ['music', 'note', 'audio', 'sound']],
        ['name' => 'Newspaper', 'component' => 'NewspaperIcon', 'category' => 'media', 'keywords' => ['newspaper', 'news', 'article', 'media']],
        ['name' => 'Office Building', 'component' => 'OfficeBuildingIcon', 'category' => 'business', 'keywords' => ['office', 'building', 'business', 'corporate']],
        ['name' => 'Paper Airplane', 'component' => 'PaperAirplaneIcon', 'category' => 'communication', 'keywords' => ['send', 'airplane', 'message', 'mail']],
        ['name' => 'Paper Clip', 'component' => 'PaperClipIcon', 'category' => 'general', 'keywords' => ['paperclip', 'attach', 'file', 'clip']],
        ['name' => 'Pause', 'component' => 'PauseIcon', 'category' => 'media', 'keywords' => ['pause', 'stop', 'break', 'halt']],
        ['name' => 'Pencil', 'component' => 'PencilIcon', 'category' => 'general', 'keywords' => ['pencil', 'edit', 'write', 'draw']],
        ['name' => 'Pencil Alt', 'component' => 'PencilAltIcon', 'category' => 'general', 'keywords' => ['pencil', 'alt', 'edit', 'write']],
        ['name' => 'Phone', 'component' => 'PhoneIcon', 'category' => 'communication', 'keywords' => ['phone', 'call', 'telephone', 'contact']],
        ['name' => 'Phone Incoming', 'component' => 'PhoneIncomingIcon', 'category' => 'communication', 'keywords' => ['phone', 'incoming', 'call', 'receive']],
        ['name' => 'Phone Missed Call', 'component' => 'PhoneMissedCallIcon', 'category' => 'communication', 'keywords' => ['phone', 'missed', 'call', 'notification']],
        ['name' => 'Phone Outgoing', 'component' => 'PhoneOutgoingIcon', 'category' => 'communication', 'keywords' => ['phone', 'outgoing', 'call', 'dial']],
        ['name' => 'Photograph', 'component' => 'PhotographIcon', 'category' => 'media', 'keywords' => ['photograph', 'photo', 'image', 'picture']],
        ['name' => 'Play', 'component' => 'PlayIcon', 'category' => 'media', 'keywords' => ['play', 'start', 'begin', 'video']],
        ['name' => 'Plus', 'component' => 'PlusIcon', 'category' => 'ui', 'keywords' => ['plus', 'add', 'create', 'increase']],
        ['name' => 'Plus Circle', 'component' => 'PlusCircleIcon', 'category' => 'ui', 'keywords' => ['plus', 'circle', 'add', 'create']],
        ['name' => 'Plus Sm', 'component' => 'PlusSmIcon', 'category' => 'ui', 'keywords' => ['plus', 'small', 'add', 'create']],
        ['name' => 'Presentation Chart Bar', 'component' => 'PresentationChartBarIcon', 'category' => 'business', 'keywords' => ['presentation', 'chart', 'bar', 'business']],
        ['name' => 'Presentation Chart Line', 'component' => 'PresentationChartLineIcon', 'category' => 'business', 'keywords' => ['presentation', 'chart', 'line', 'business']],
        ['name' => 'Printer', 'component' => 'PrinterIcon', 'category' => 'general', 'keywords' => ['printer', 'print', 'output', 'paper']],
        ['name' => 'Puzzle', 'component' => 'PuzzleIcon', 'category' => 'general', 'keywords' => ['puzzle', 'piece', 'solution', 'problem']],
        ['name' => 'Qrcode', 'component' => 'QrcodeIcon', 'category' => 'technology', 'keywords' => ['qrcode', 'qr', 'code', 'scan']],
        ['name' => 'Question Mark Circle', 'component' => 'QuestionMarkCircleIcon', 'category' => 'status', 'keywords' => ['question', 'help', 'circle', 'support']],
        ['name' => 'Receipt Refund', 'component' => 'ReceiptRefundIcon', 'category' => 'business', 'keywords' => ['receipt', 'refund', 'money', 'return']],
        ['name' => 'Receipt Tax', 'component' => 'ReceiptTaxIcon', 'category' => 'business', 'keywords' => ['receipt', 'tax', 'money', 'payment']],
        ['name' => 'Refresh', 'component' => 'RefreshIcon', 'category' => 'ui', 'keywords' => ['refresh', 'reload', 'update', 'sync']],
        ['name' => 'Reply', 'component' => 'ReplyIcon', 'category' => 'communication', 'keywords' => ['reply', 'respond', 'answer', 'back']],
        ['name' => 'Rewind', 'component' => 'RewindIcon', 'category' => 'media', 'keywords' => ['rewind', 'back', 'previous', 'reverse']],
        ['name' => 'Rss', 'component' => 'RssIcon', 'category' => 'communication', 'keywords' => ['rss', 'feed', 'subscribe', 'news']],
        ['name' => 'Save', 'component' => 'SaveIcon', 'category' => 'general', 'keywords' => ['save', 'disk', 'store', 'keep']],
        ['name' => 'Save As', 'component' => 'SaveAsIcon', 'category' => 'general', 'keywords' => ['save', 'as', 'copy', 'duplicate']],
        ['name' => 'Scale', 'component' => 'ScaleIcon', 'category' => 'business', 'keywords' => ['scale', 'balance', 'justice', 'weight']],
        ['name' => 'Scissors', 'component' => 'ScissorsIcon', 'category' => 'general', 'keywords' => ['scissors', 'cut', 'trim', 'clip']],
        ['name' => 'Search', 'component' => 'SearchIcon', 'category' => 'ui', 'keywords' => ['search', 'find', 'look', 'magnify']],
        ['name' => 'Search Circle', 'component' => 'SearchCircleIcon', 'category' => 'ui', 'keywords' => ['search', 'circle', 'find', 'look']],
        ['name' => 'Selector', 'component' => 'SelectorIcon', 'category' => 'ui', 'keywords' => ['selector', 'choose', 'pick', 'select']],
        ['name' => 'Server', 'component' => 'ServerIcon', 'category' => 'technology', 'keywords' => ['server', 'computer', 'host', 'data']],
        ['name' => 'Share', 'component' => 'ShareIcon', 'category' => 'communication', 'keywords' => ['share', 'send', 'distribute', 'spread']],
        ['name' => 'Shield Check', 'component' => 'ShieldCheckIcon', 'category' => 'security', 'keywords' => ['shield', 'check', 'security', 'protected']],
        ['name' => 'Shield Exclamation', 'component' => 'ShieldExclamationIcon', 'category' => 'security', 'keywords' => ['shield', 'exclamation', 'warning', 'security']],
        ['name' => 'Shopping Bag', 'component' => 'ShoppingBagIcon', 'category' => 'business', 'keywords' => ['shopping', 'bag', 'buy', 'purchase']],
        ['name' => 'Shopping Cart', 'component' => 'ShoppingCartIcon', 'category' => 'business', 'keywords' => ['shopping', 'cart', 'buy', 'purchase']],
        ['name' => 'Sort Ascending', 'component' => 'SortAscendingIcon', 'category' => 'ui', 'keywords' => ['sort', 'ascending', 'order', 'arrange']],
        ['name' => 'Sort Descending', 'component' => 'SortDescendingIcon', 'category' => 'ui', 'keywords' => ['sort', 'descending', 'order', 'arrange']],
        ['name' => 'Sparkles', 'component' => 'SparklesIcon', 'category' => 'general', 'keywords' => ['sparkles', 'magic', 'special', 'stars']],
        ['name' => 'Speakerphone', 'component' => 'SpeakerphoneIcon', 'category' => 'communication', 'keywords' => ['speakerphone', 'announcement', 'loud', 'megaphone']],
        ['name' => 'Star', 'component' => 'StarIcon', 'category' => 'general', 'keywords' => ['star', 'favorite', 'rating', 'bookmark']],
        ['name' => 'Status Offline', 'component' => 'StatusOfflineIcon', 'category' => 'status', 'keywords' => ['status', 'offline', 'disconnected', 'unavailable']],
        ['name' => 'Status Online', 'component' => 'StatusOnlineIcon', 'category' => 'status', 'keywords' => ['status', 'online', 'connected', 'available']],
        ['name' => 'Stop', 'component' => 'StopIcon', 'category' => 'media', 'keywords' => ['stop', 'halt', 'end', 'terminate']],
        ['name' => 'Sun', 'component' => 'SunIcon', 'category' => 'general', 'keywords' => ['sun', 'light', 'day', 'bright']],
        ['name' => 'Support', 'component' => 'SupportIcon', 'category' => 'communication', 'keywords' => ['support', 'help', 'assistance', 'service']],
        ['name' => 'Switch Horizontal', 'component' => 'SwitchHorizontalIcon', 'category' => 'ui', 'keywords' => ['switch', 'horizontal', 'toggle', 'change']],
        ['name' => 'Switch Vertical', 'component' => 'SwitchVerticalIcon', 'category' => 'ui', 'keywords' => ['switch', 'vertical', 'toggle', 'change']],
        ['name' => 'Table', 'component' => 'TableIcon', 'category' => 'ui', 'keywords' => ['table', 'grid', 'data', 'organize']],
        ['name' => 'Tag', 'component' => 'TagIcon', 'category' => 'general', 'keywords' => ['tag', 'label', 'mark', 'category']],
        ['name' => 'Template', 'component' => 'TemplateIcon', 'category' => 'general', 'keywords' => ['template', 'layout', 'design', 'structure']],
        ['name' => 'Terminal', 'component' => 'TerminalIcon', 'category' => 'technology', 'keywords' => ['terminal', 'console', 'command', 'cli']],
        ['name' => 'Thumb Down', 'component' => 'ThumbDownIcon', 'category' => 'general', 'keywords' => ['thumb', 'down', 'dislike', 'negative']],
        ['name' => 'Thumb Up', 'component' => 'ThumbUpIcon', 'category' => 'general', 'keywords' => ['thumb', 'up', 'like', 'positive']],
        ['name' => 'Ticket', 'component' => 'TicketIcon', 'category' => 'general', 'keywords' => ['ticket', 'event', 'admission', 'pass']],
        ['name' => 'Translate', 'component' => 'TranslateIcon', 'category' => 'communication', 'keywords' => ['translate', 'language', 'convert', 'international']],
        ['name' => 'Trash', 'component' => 'TrashIcon', 'category' => 'ui', 'keywords' => ['trash', 'delete', 'remove', 'bin']],
        ['name' => 'Trending Down', 'component' => 'TrendingDownIcon', 'category' => 'data', 'keywords' => ['trending', 'down', 'decrease', 'decline']],
        ['name' => 'Trending Up', 'component' => 'TrendingUpIcon', 'category' => 'data', 'keywords' => ['trending', 'up', 'increase', 'growth']],
        ['name' => 'Truck', 'component' => 'TruckIcon', 'category' => 'general', 'keywords' => ['truck', 'delivery', 'transport', 'vehicle']],
        ['name' => 'Upload', 'component' => 'UploadIcon', 'category' => 'general', 'keywords' => ['upload', 'send', 'transfer', 'share']],
        ['name' => 'User', 'component' => 'UserIcon', 'category' => 'general', 'keywords' => ['user', 'person', 'profile', 'account']],
        ['name' => 'User Add', 'component' => 'UserAddIcon', 'category' => 'general', 'keywords' => ['user', 'add', 'new', 'invite']],
        ['name' => 'User Circle', 'component' => 'UserCircleIcon', 'category' => 'general', 'keywords' => ['user', 'circle', 'profile', 'avatar']],
        ['name' => 'User Group', 'component' => 'UserGroupIcon', 'category' => 'general', 'keywords' => ['user', 'group', 'team', 'people']],
        ['name' => 'User Remove', 'component' => 'UserRemoveIcon', 'category' => 'general', 'keywords' => ['user', 'remove', 'delete', 'kick']],
        ['name' => 'Users', 'component' => 'UsersIcon', 'category' => 'general', 'keywords' => ['users', 'people', 'group', 'team']],
        ['name' => 'Variable', 'component' => 'VariableIcon', 'category' => 'technology', 'keywords' => ['variable', 'code', 'programming', 'data']],
        ['name' => 'Video Camera', 'component' => 'VideoCameraIcon', 'category' => 'media', 'keywords' => ['video', 'camera', 'record', 'film']],
        ['name' => 'View Boards', 'component' => 'ViewBoardsIcon', 'category' => 'ui', 'keywords' => ['view', 'boards', 'kanban', 'organize']],
        ['name' => 'View Grid', 'component' => 'ViewGridIcon', 'category' => 'ui', 'keywords' => ['view', 'grid', 'layout', 'organize']],
        ['name' => 'View Grid Add', 'component' => 'ViewGridAddIcon', 'category' => 'ui', 'keywords' => ['view', 'grid', 'add', 'create']],
        ['name' => 'View List', 'component' => 'ViewListIcon', 'category' => 'ui', 'keywords' => ['view', 'list', 'layout', 'organize']],
        ['name' => 'Volume Off', 'component' => 'VolumeOffIcon', 'category' => 'media', 'keywords' => ['volume', 'off', 'mute', 'silent']],
        ['name' => 'Volume Up', 'component' => 'VolumeUpIcon', 'category' => 'media', 'keywords' => ['volume', 'up', 'loud', 'sound']],
        ['name' => 'Wifi', 'component' => 'WifiIcon', 'category' => 'technology', 'keywords' => ['wifi', 'wireless', 'internet', 'connection']],
        ['name' => 'X', 'component' => 'XIcon', 'category' => 'ui', 'keywords' => ['x', 'close', 'cancel', 'remove']],
        ['name' => 'X Circle', 'component' => 'XCircleIcon', 'category' => 'ui', 'keywords' => ['x', 'circle', 'close', 'cancel']],
        ['name' => 'Zoom In', 'component' => 'ZoomInIcon', 'category' => 'ui', 'keywords' => ['zoom', 'in', 'magnify', 'enlarge']],
        ['name' => 'Zoom Out', 'component' => 'ZoomOutIcon', 'category' => 'ui', 'keywords' => ['zoom', 'out', 'shrink', 'reduce']],
    ],
    
    /**
     * 圖標樣式
     * 
     * Hero Icons 支援 outline 和 solid 兩種樣式
     * outline: 線條風格，適合大部分 UI 場景
     * solid: 實心風格，適合需要強調的場景
     */
    'styles' => ['outline', 'solid'],
    
    /**
     * 預設樣式
     */
    'default_style' => 'outline',
    
    /**
     * 分類定義
     */
    'categories' => [
        'general' => '一般',
        'navigation' => '導航',
        'ui' => '使用者介面',
        'communication' => '溝通',
        'media' => '媒體',
        'business' => '商業',
        'technology' => '科技',
        'security' => '安全',
        'status' => '狀態',
        'data' => '資料',
        'design' => '設計',
        'science' => '科學',
    ],
];